import type {LessonBeat} from '../../types';

export const lessonPlan: LessonBeat[] = [
  {
    id: 'intro',
    kind: 'intro',
    start: 0,
    end: 7.6,
    title: 'Engineering Systems',
    subtitle: 'Consistency in practice',
    takeaway: 'From distributed consistency theory to real engineering decisions.',
  },
  {
    id: 'practical-shift',
    kind: 'practical-shift',
    start: 7.6,
    end: 17.44,
    title: 'Theory Becomes Practice',
    subtitle: 'The models matter when you can place them inside a system.',
    takeaway: 'Today is about applying the vocabulary.',
  },
  {
    id: 'opening-question',
    kind: 'opening-question',
    start: 17.44,
    end: 24.64,
    title: 'The Production Question',
    subtitle: 'Look at a massive e-commerce site.',
    takeaway: 'What consistency model does it use?',
  },
  {
    id: 'binary-trap',
    kind: 'opening-question',
    start: 24.64,
    end: 31.82,
    title: 'Strong Or Eventual?',
    subtitle: 'It feels like it must be one or the other.',
    takeaway: 'That framing is the trap.',
  },
  {
    id: 'answer',
    kind: 'myth',
    start: 31.82,
    end: 37.74,
    title: 'Both, And Neither',
    subtitle: 'The real answer is more interesting.',
    takeaway: 'One system can carry multiple guarantees.',
  },
  {
    id: 'mosaic',
    kind: 'mosaic',
    start: 37.74,
    end: 45.2,
    title: 'Patchwork System',
    subtitle: 'Large systems are mosaics, not monoliths.',
    takeaway: 'Engineering craft is picking the right piece for the right spot.',
  },
  {
    id: 'mosaic-contracts',
    kind: 'mosaic-contracts',
    start: 45.2,
    end: 52.7,
    title: 'Patchwork System',
    subtitle: 'Each feature carries its own contract.',
    takeaway: 'A platform is a bundle of local consistency decisions.',
  },
  {
    id: 'vocabulary',
    kind: 'vocabulary',
    start: 52.7,
    end: 63,
    title: 'The Vocabulary',
    subtitle: 'Strong, eventual, read-your-writes, and causal.',
    takeaway: 'These are tools, not global presets.',
  },
  {
    id: 'vocabulary-spectrum',
    kind: 'vocabulary-spectrum',
    start: 63,
    end: 73.38,
    title: 'The Vocabulary',
    subtitle: 'Different names mean different guarantees.',
    takeaway: 'Name the guarantee before choosing the architecture.',
  },
  {
    id: 'agenda',
    kind: 'agenda',
    start: 73.38,
    end: 82.9,
    title: 'Today\'s Flow',
    subtitle: 'Myth, example, framework, spectrum, availability.',
    takeaway: 'A practical design review for consistency.',
  },
  {
    id: 'agenda-examples',
    kind: 'agenda-examples',
    start: 82.9,
    end: 92.42,
    title: 'Today\'s Flow',
    subtitle: 'We will keep tying the model back to real features.',
    takeaway: 'Examples make the consistency choice concrete.',
  },
  {
    id: 'principle',
    kind: 'principle',
    start: 92.42,
    end: 98.8,
    title: 'Do Not Pick One',
    subtitle: 'Do not apply one consistency model everywhere.',
    takeaway: 'The system is not the unit of choice.',
  },
  {
    id: 'principle-scope',
    kind: 'principle-scope',
    start: 98.8,
    end: 105,
    title: 'Do Not Pick One',
    subtitle: 'Choose at the feature boundary.',
    takeaway: 'The feature is the unit of consistency design.',
  },
  {
    id: 'feature-level',
    kind: 'feature-contrast',
    start: 105,
    end: 112.6,
    title: 'Feature-Level Decision',
    subtitle: 'Financial transactions and like buttons need different guarantees.',
    takeaway: 'The feature determines the consistency contract.',
  },
  {
    id: 'like-button-example',
    kind: 'like-button-example',
    start: 112.6,
    end: 120.38,
    title: 'Like Button',
    subtitle: 'A tiny delay is acceptable.',
    takeaway: 'Use eventual consistency when freshness is not critical.',
  },
  {
    id: 'commerce-map',
    kind: 'commerce-map',
    start: 120.38,
    end: 127.78,
    title: 'E-Commerce Map',
    subtitle: 'Break the platform down component by component.',
    takeaway: 'Each surface gets its own decision.',
  },
  {
    id: 'inventory',
    kind: 'inventory',
    start: 127.78,
    end: 133.12,
    title: 'Inventory Service',
    subtitle: 'The heart of the operation.',
    takeaway: 'The rule is simple: stock must be correct.',
  },
  {
    id: 'inventory-rule',
    kind: 'inventory-rule',
    start: 133.12,
    end: 140.43,
    title: 'No Overselling',
    subtitle: 'If two items remain, only two people can buy them.',
    takeaway: 'Strong consistency is the only real choice.',
  },
  {
    id: 'inventory-race',
    kind: 'inventory-race',
    start: 140.43,
    end: 147.74,
    title: 'No Overselling',
    subtitle: 'The third buyer must be rejected.',
    takeaway: 'Correctness protects the business invariant.',
  },
  {
    id: 'reviews',
    kind: 'reviews',
    start: 147.74,
    end: 158.94,
    title: 'Product Reviews',
    subtitle: 'Does every user need to see a new review instantly?',
    takeaway: 'A small delay is fine.',
  },
  {
    id: 'review-choice',
    kind: 'review-choice',
    start: 158.94,
    end: 168.84,
    title: 'Loosen The Reins',
    subtitle: 'Keep the site up and fast.',
    takeaway: 'Use eventual consistency for review visibility.',
  },
  {
    id: 'profile',
    kind: 'profile',
    start: 168.84,
    end: 178.74,
    title: 'Profile Updates',
    subtitle: 'After save, users expect to see their own new address.',
    takeaway: 'Immediate self-read matters.',
  },
  {
    id: 'profile-trust',
    kind: 'profile-trust',
    start: 178.74,
    end: 187.64,
    title: 'Read Your Writes',
    subtitle: 'Trust without synchronizing the whole globe.',
    takeaway: 'Guarantee the writer sees their own change.',
  },
  {
    id: 'comments',
    kind: 'comments',
    start: 187.64,
    end: 199.28,
    title: 'Comment Threads',
    subtitle: 'Replies need cause-and-effect order.',
    takeaway: 'Conversation order is part of correctness.',
  },
  {
    id: 'comments-order',
    kind: 'comments-order',
    start: 199.28,
    end: 208.78,
    title: 'Causal Consistency',
    subtitle: 'Logical conversation flow without strict global ordering.',
    takeaway: 'Preserve causality where users depend on it.',
  },
  {
    id: 'analytics',
    kind: 'analytics',
    start: 208.78,
    end: 215.6,
    title: 'Analytics Dashboard',
    subtitle: '10,002 active users vs 10,005.',
    takeaway: 'The exact number rarely changes the decision.',
  },
  {
    id: 'analytics-impact',
    kind: 'analytics-impact',
    start: 215.6,
    end: 222.42,
    title: 'Analytics Dashboard',
    subtitle: 'The business action usually stays the same.',
    takeaway: 'Low impact means freshness can relax.',
  },
  {
    id: 'analytics-staleness',
    kind: 'analytics-staleness',
    start: 222.42,
    end: 229.5,
    title: 'Relax Guarantees',
    subtitle: 'Fast beats perfectly precise when impact is tiny.',
    takeaway: 'Weak or eventual consistency is enough here.',
  },
  {
    id: 'analytics-speed',
    kind: 'analytics-speed',
    start: 229.5,
    end: 236.52,
    title: 'Relax Guarantees',
    subtitle: 'Keep the dashboard responsive.',
    takeaway: 'Spend coordination only where precision matters.',
  },
  {
    id: 'choose-question',
    kind: 'tradeoff',
    start: 236.52,
    end: 245.78,
    title: 'How Do You Choose?',
    subtitle: 'Every choice is a trade-off.',
    takeaway: 'Correctness has a price.',
  },
  {
    id: 'coordination-cost',
    kind: 'coordination-cost',
    start: 245.78,
    end: 255.56,
    title: 'Coordination Cost',
    subtitle: 'Stronger guarantees require more server coordination.',
    takeaway: 'More coordination means more latency.',
  },
  {
    id: 'coordination-pressure',
    kind: 'coordination-pressure',
    start: 255.56,
    end: 265.38,
    title: 'Coordination Cost',
    subtitle: 'Every extra agreement point adds availability pressure.',
    takeaway: 'Correctness has to be bought intentionally.',
  },
  {
    id: 'framework',
    kind: 'decision-framework',
    start: 265.38,
    end: 268.46,
    title: 'Three-Step Model',
    subtitle: 'A compact way to choose with intent.',
    takeaway: 'Risk, impact, then sufficient guarantee.',
  },
  {
    id: 'risk-step',
    kind: 'risk-step',
    start: 268.46,
    end: 276.04,
    title: 'Step 1: Risk',
    subtitle: 'What is the worst thing if this data is stale?',
    takeaway: 'Start with failure mode.',
  },
  {
    id: 'business-step',
    kind: 'business-step',
    start: 276.04,
    end: 281.5,
    title: 'Step 2: Impact',
    subtitle: 'Money, security, trust, and UX.',
    takeaway: 'Risk only matters through business consequences.',
  },
  {
    id: 'choose-step',
    kind: 'choose-step',
    start: 281.5,
    end: 287.9,
    title: 'Step 3: Choose',
    subtitle: 'Pick the sufficient model, not the strongest one.',
    takeaway: 'Do not pay for guarantees you do not need.',
  },
  {
    id: 'sufficient-step',
    kind: 'sufficient-step',
    start: 287.9,
    end: 294.28,
    title: 'Step 3: Choose',
    subtitle: 'The right answer is the cheapest guarantee that still works.',
    takeaway: 'Sufficient beats strongest in practical design.',
  },
  {
    id: 'spectrum',
    kind: 'spectrum-strong',
    start: 294.28,
    end: 300.8,
    title: 'Strong Extreme',
    subtitle: 'Maximum correctness, highest coordination cost.',
    takeaway: 'Strong consistency buys certainty.',
  },
  {
    id: 'spectrum-coordination',
    kind: 'spectrum-coordination',
    start: 300.8,
    end: 307.3,
    title: 'Strong Extreme',
    subtitle: 'Certainty comes from waiting for agreement.',
    takeaway: 'The left side of the spectrum is expensive.',
  },
  {
    id: 'spectrum-middle',
    kind: 'spectrum-middle',
    start: 307.3,
    end: 317.7,
    title: 'Middle Of The Spectrum',
    subtitle: 'Causal, read-your-writes, and eventual models.',
    takeaway: 'Trade some correctness for performance and availability.',
  },
  {
    id: 'spectrum-weak',
    kind: 'spectrum-weak',
    start: 317.7,
    end: 326.62,
    title: 'Weak Extreme',
    subtitle: 'Maximum availability, fewest guarantees.',
    takeaway: 'Weak consistency is still a deliberate choice.',
  },
  {
    id: 'final-lesson',
    kind: 'final-lesson',
    start: 326.62,
    end: 336.84,
    title: 'The Lesson',
    subtitle: 'Consistency is not a default setting.',
    takeaway: 'It is a deliberate design decision.',
  },
  {
    id: 'decision-checklist',
    kind: 'decision-checklist',
    start: 336.84,
    end: 347.06,
    title: 'Decision Checklist',
    subtitle: 'Risk, business impact, and the sufficient guarantee.',
    takeaway: 'Choose the weakest model that still protects the product.',
  },
  {
    id: 'tradeoff-recap',
    kind: 'tradeoff-recap',
    start: 347.06,
    end: 353.76,
    title: 'The Other Side',
    subtitle: 'Every consistency choice touched performance and availability.',
    takeaway: 'That points us to the next topic.',
  },
  {
    id: 'availability-bridge',
    kind: 'availability-bridge',
    start: 353.76,
    end: 360.46,
    title: 'The Other Side',
    subtitle: 'The next question is how systems stay up.',
    takeaway: 'Availability is the next design dimension.',
  },
  {
    id: 'next-series',
    kind: 'next-series',
    start: 360.46,
    end: 365.78,
    title: 'Next Series',
    subtitle: 'Availability patterns.',
    takeaway: 'Now we study how systems stay up.',
  },
  {
    id: 'availability-preview',
    kind: 'availability-preview',
    start: 365.78,
    end: 373.84,
    title: 'Resilient Software',
    subtitle: 'Failures, recovery, and surviving the real world.',
    takeaway: 'Availability is the other half of the equation.',
  },
  {
    id: 'failure-preview',
    kind: 'failure-preview',
    start: 373.84,
    end: 381.88,
    title: 'Failure Patterns',
    subtitle: 'Retries, failover, replication, and graceful degradation.',
    takeaway: 'Next we study how systems stay up.',
  },
  {
    id: 'closing',
    kind: 'closing',
    start: 381.88,
    end: 386.82,
    title: 'Thanks For Watching',
    subtitle: 'We are just getting started.',
    takeaway: 'End of the consistency series.',
  },
];
