import type {LessonBeat} from '../../types';

export const lessonPlan: LessonBeat[] = [
  {
    id: 'sap-00',
    kind: 'sap-screen',
    start: 0,
    end: 1.61,
    title: 'Engineering Systems',
    subtitle: 'Availability Patterns #6',
    takeaway: 'Dependency shape sets up the availability lesson.',
  },
  {
    id: 'sap-01',
    kind: 'sap-screen',
    start: 1.61,
    end: 4.69,
    title: 'Series vs Parallel Availability',
    subtitle: 'How dependency shape changes uptime math.',
    takeaway: 'Availability depends on how components are connected.',
  },
  {
    id: 'sap-02',
    kind: 'sap-screen',
    start: 4.69,
    end: 9.67,
    title: 'FoodDash Is Stronger',
    subtitle: 'Single points of failure were removed.',
    takeaway: 'The platform is more resilient than it used to be.',
  },
  {
    id: 'sap-03',
    kind: 'sap-screen',
    start: 9.67,
    end: 15.17,
    title: 'Targets Are Known',
    subtitle: 'Failover and the famous nines are already on the board.',
    takeaway: 'The team has targets, redundancy, and recovery vocabulary.',
  },
  {
    id: 'sap-04',
    kind: 'sap-screen',
    start: 15.17,
    end: 20.39,
    title: 'One Strange Question',
    subtitle: 'A resilient system can still hide a math trap.',
    takeaway: 'Availability is not just a property of each isolated part.',
  },
  {
    id: 'sap-05',
    kind: 'sap-screen',
    start: 20.39,
    end: 24.63,
    title: 'Team Meeting',
    subtitle: 'A junior engineer asks the obvious question.',
    takeaway: 'The trap starts with a reasonable assumption.',
  },
  {
    id: 'sap-06',
    kind: 'sap-screen',
    start: 24.63,
    end: 31.15,
    title: '99.9 Plus 99.9?',
    subtitle: 'Does each component target become the whole system target?',
    takeaway: 'Component availability does not automatically transfer to the system.',
  },
  {
    id: 'sap-07',
    kind: 'sap-screen',
    start: 31.15,
    end: 37.83,
    title: 'Reasonable But Wrong',
    subtitle: 'Everyone nods, then the architecture math pushes back.',
    takeaway: 'The system shape decides how component numbers combine.',
  },
  {
    id: 'sap-08',
    kind: 'sap-screen',
    start: 37.83,
    end: 44.21,
    title: 'Strip Down FoodDash',
    subtitle: 'Start with the smallest request path.',
    takeaway: 'A simple system makes the dependency rule visible.',
  },
  {
    id: 'sap-09',
    kind: 'sap-screen',
    start: 44.21,
    end: 52.67,
    title: 'Menu Request Path',
    subtitle: 'Customer to API, API to database, database back to menu.',
    takeaway: 'The customer sees a menu only if the full chain works.',
  },
  {
    id: 'sap-10',
    kind: 'sap-screen',
    start: 52.67,
    end: 62.91,
    title: 'Two Good Components',
    subtitle: 'API is 99.9%. Database is 99.9%.',
    takeaway: 'Two strong parts still need combined availability math.',
  },
  {
    id: 'sap-11',
    kind: 'sap-screen',
    start: 62.91,
    end: 70.53,
    title: 'The Catch',
    subtitle: 'The API absolutely must be working.',
    takeaway: 'A required dependency becomes part of the availability equation.',
  },
  {
    id: 'sap-12',
    kind: 'sap-screen',
    start: 70.53,
    end: 75.83,
    title: 'Both, Not Either',
    subtitle: 'The API and database must be healthy at the same time.',
    takeaway: 'Series availability is an AND relationship.',
  },
  {
    id: 'sap-13',
    kind: 'sap-screen',
    start: 75.83,
    end: 83.71,
    title: 'Database Down',
    subtitle: 'API is healthy, but the request still fails.',
    takeaway: 'One broken dependency is enough to lose the request.',
  },
  {
    id: 'sap-14',
    kind: 'sap-screen',
    start: 83.71,
    end: 89.23,
    title: 'API Down',
    subtitle: 'Database is healthy, but the request still fails.',
    takeaway: 'The failed component can change; the user outcome is the same.',
  },
  {
    id: 'sap-15',
    kind: 'sap-screen',
    start: 89.23,
    end: 96.01,
    title: 'Same Customer Pain',
    subtitle: 'The customer cannot order food either way.',
    takeaway: 'Availability is judged at the user workflow, not the component dashboard.',
  },
  {
    id: 'sap-16',
    kind: 'sap-screen',
    start: 96.01,
    end: 103.55,
    title: 'Series System',
    subtitle: 'A request must pass through every component in the chain.',
    takeaway: 'Every required hop multiplies the chance of failure.',
  },
  {
    id: 'sap-17',
    kind: 'sap-screen',
    start: 103.55,
    end: 109.53,
    title: 'Weakest Link',
    subtitle: 'If one link breaks, the whole request fails.',
    takeaway: 'A series chain is only as strong as the weakest required dependency.',
  },
  {
    id: 'sap-18',
    kind: 'sap-screen',
    start: 109.53,
    end: 115.61,
    title: 'FoodDash Grows',
    subtitle: 'The system is no longer just API plus database.',
    takeaway: 'Real product growth creates longer request paths.',
  },
  {
    id: 'sap-19',
    kind: 'sap-screen',
    start: 115.61,
    end: 124.27,
    title: 'Longer Request Chain',
    subtitle: 'Load balancer, API, database, payment, notification.',
    takeaway: 'More services means more required hops.',
  },
  {
    id: 'sap-20',
    kind: 'sap-screen',
    start: 124.27,
    end: 132.71,
    title: 'More Failure Slots',
    subtitle: 'Every component adds another opportunity for failure.',
    takeaway: 'Each required dependency adds another way the request can fail.',
  },
  {
    id: 'sap-21',
    kind: 'sap-screen',
    start: 132.71,
    end: 140.13,
    title: 'Powerful But Fragile',
    subtitle: 'More features can make the app less available.',
    takeaway: 'Capability and availability can move in opposite directions.',
  },
  {
    id: 'sap-22',
    kind: 'sap-screen',
    start: 140.13,
    end: 148.55,
    title: 'Availability Multiplies',
    subtitle: 'Four or five 99.9% components produce a lower system number.',
    takeaway: 'Series availability is the product of required component availability.',
  },
  {
    id: 'sap-23',
    kind: 'sap-screen',
    start: 148.55,
    end: 156.67,
    title: 'Chipped Away',
    subtitle: 'Each dependency slowly reduces the whole system target.',
    takeaway: 'Small individual risks accumulate across the chain.',
  },
  {
    id: 'sap-24',
    kind: 'sap-screen',
    start: 156.67,
    end: 161.37,
    title: 'Modern Apps',
    subtitle: 'Distributed systems are collections of services.',
    takeaway: 'The topology matters as much as the service list.',
  },
  {
    id: 'sap-25',
    kind: 'sap-screen',
    start: 161.37,
    end: 168.31,
    title: 'Capability And Risk',
    subtitle: 'Every dependency adds capability and also adds risk.',
    takeaway: 'Useful dependencies still need availability discipline.',
  },
  {
    id: 'sap-26',
    kind: 'sap-screen',
    start: 168.31,
    end: 174.13,
    title: 'Wrong Direction',
    subtitle: 'FoodDash wants power without losing availability.',
    takeaway: 'Do not let feature growth quietly lower uptime.',
  },
  {
    id: 'sap-27',
    kind: 'sap-screen',
    start: 174.13,
    end: 180.89,
    title: 'Parallel Fix',
    subtitle: 'Redundancy creates alternative paths.',
    takeaway: 'Parallel design reduces how many things absolutely must work.',
  },
  {
    id: 'sap-28',
    kind: 'sap-screen',
    start: 180.89,
    end: 188.69,
    title: 'Two Databases',
    subtitle: 'Primary database plus replica database.',
    takeaway: 'The database layer gains another path to state.',
  },
  {
    id: 'sap-29',
    kind: 'sap-screen',
    start: 188.69,
    end: 193.37,
    title: 'Aha Moment',
    subtitle: 'The request no longer depends on one database.',
    takeaway: 'A single database is no longer the only route to success.',
  },
  {
    id: 'sap-30',
    kind: 'sap-screen',
    start: 193.37,
    end: 201.31,
    title: 'Database B Takes Over',
    subtitle: 'If database A fails, database B can serve the request.',
    takeaway: 'Parallel paths turn a component failure into a recoverable event.',
  },
  {
    id: 'sap-31',
    kind: 'sap-screen',
    start: 201.31,
    end: 206.49,
    title: 'Series vs Parallel',
    subtitle: 'Series needs every component. Parallel needs one healthy path.',
    takeaway: 'The availability formula flips from AND to OR.',
  },
  {
    id: 'sap-32',
    kind: 'sap-screen',
    start: 206.49,
    end: 216.57,
    title: 'One Bridge',
    subtitle: 'If the only bridge collapses, there is no route across.',
    takeaway: 'A single route creates a series dependency.',
  },
  {
    id: 'sap-33',
    kind: 'sap-screen',
    start: 216.57,
    end: 223.95,
    title: 'Two Bridges',
    subtitle: 'If one bridge closes, the alternate route still works.',
    takeaway: 'Parallel routes keep the destination reachable.',
  },
  {
    id: 'sap-34',
    kind: 'sap-screen',
    start: 223.95,
    end: 232.59,
    title: 'Past Topics Connect',
    subtitle: 'Replication and redundant servers create parallel paths.',
    takeaway: 'The earlier patterns are ways to remove single required paths.',
  },
  {
    id: 'sap-35',
    kind: 'sap-screen',
    start: 232.59,
    end: 240.47,
    title: 'Alternative Networks',
    subtitle: 'Multi-region systems improve uptime with more routes.',
    takeaway: 'The expensive infrastructure buys independent success paths.',
  },
  {
    id: 'sap-36',
    kind: 'sap-screen',
    start: 240.47,
    end: 246.77,
    title: 'Design Goal',
    subtitle: 'Reduce must-work components. Increase success paths.',
    takeaway: 'High availability comes from fewer hard dependencies and more options.',
  },
  {
    id: 'sap-37',
    kind: 'sap-screen',
    start: 246.77,
    end: 254.81,
    title: 'Recap: Series',
    subtitle: 'Every component must be healthy.',
    takeaway: 'Series chains decrease overall availability.',
  },
  {
    id: 'sap-38',
    kind: 'sap-screen',
    start: 254.81,
    end: 259.19,
    title: 'Recap: Parallel',
    subtitle: 'Only one path needs to work.',
    takeaway: 'Parallel infrastructure improves recovery odds.',
  },
  {
    id: 'sap-39',
    kind: 'sap-screen',
    start: 259.19,
    end: 266.29,
    title: 'Redundancy Transforms Chains',
    subtitle: 'Fragile series paths become highly available parallel systems.',
    takeaway: 'Redundancy builds uptime back up by creating alternatives.',
  },
  {
    id: 'sap-40',
    kind: 'sap-screen',
    start: 266.29,
    end: 275.37,
    title: 'Next Question',
    subtitle: 'FoodDash has multiple healthy redundant servers.',
    takeaway: 'Parallel capacity creates a routing decision.',
  },
  {
    id: 'sap-41',
    kind: 'sap-screen',
    start: 275.37,
    end: 281.71,
    title: 'Who Gets The Request?',
    subtitle: 'Which healthy server handles the next customer?',
    takeaway: 'Availability also depends on how traffic is assigned.',
  },
  {
    id: 'sap-42',
    kind: 'sap-screen',
    start: 281.71,
    end: 289.17,
    title: 'Avoid Overload',
    subtitle: 'Do not overwhelm one server while others sit idle.',
    takeaway: 'The next availability pattern is load balancing.',
  },
  {
    id: 'sap-43',
    kind: 'closing',
    start: 289.17,
    end: 296,
    title: 'Engineering Systems',
    subtitle: 'See you in the next explainer.',
    takeaway: 'Thanks for watching.',
  },
];
