import type {LessonBeat} from '../../types';

export const lessonPlan: LessonBeat[] = [
  {id: 'lb-01', kind: 'lb-screen', start: 0, end: 6.73, title: 'Engineering Systems', subtitle: 'Availability Patterns #7 · Load Balancing', takeaway: 'The app tier is still one machine.'},
  {id: 'lb-02', kind: 'lb-screen', start: 7.09, end: 14.11, title: 'Database Failover', subtitle: 'Earlier availability work protects FoodDash state.', takeaway: 'Resilient dependencies do not solve compute capacity.'},
  {id: 'lb-03', kind: 'lb-screen', start: 14.33, end: 24.51, title: 'The Challenge Of Success', subtitle: 'The next failure mode comes from demand.', takeaway: 'A robust system can still saturate.'},
  {id: 'lb-04', kind: 'lb-screen', start: 25.17, end: 32.81, title: 'FoodDash Goes Viral', subtitle: 'Thousands of customers open the app every minute.', takeaway: 'Demand rate becomes infrastructure pressure.'},
  {id: 'lb-05', kind: 'lb-screen', start: 33.19, end: 40.39, title: 'Marketplace Rush', subtitle: 'Customers, restaurants, and drivers accelerate together.', takeaway: 'Product growth concentrates backend work.'},
  {id: 'lb-06', kind: 'lb-screen', start: 40.69, end: 50.85, title: 'Success Disaster', subtitle: 'One application server receives the entire spike.', takeaway: 'A single compute node becomes the bottleneck.'},
  {id: 'lb-07', kind: 'lb-screen', start: 51.35, end: 58.19, title: 'Saturation Telemetry', subtitle: 'CPU, memory, queue, and latency rise together.', takeaway: 'Resource pressure turns into slow responses.'},
  {id: 'lb-08', kind: 'lb-screen', start: 58.37, end: 66.63, title: 'Users Feel It', subtitle: 'Slow infrastructure becomes failed orders.', takeaway: 'Availability is measured at the user workflow.'},
  {id: 'lb-09', kind: 'lb-screen', start: 66.87, end: 74.21, title: 'Buy A Bigger Server', subtitle: 'The obvious first response is more hardware.', takeaway: 'Vertical scaling upgrades one machine.'},
  {id: 'lb-10', kind: 'lb-screen', start: 74.55, end: 81.63, title: 'Scale Up', subtitle: 'More CPU and RAM buy temporary capacity.', takeaway: 'Capacity rises, but cost rises too.'},
  {id: 'lb-11', kind: 'lb-screen', start: 81.63, end: 86.79, title: 'Temporary Relief', subtitle: 'The upgraded server catches its breath.', takeaway: 'Vertical scaling postpones saturation.'},
  {id: 'lb-12', kind: 'lb-screen', start: 86.97, end: 97.15, title: 'The Wall Returns', subtitle: 'Demand catches the larger server again.', takeaway: 'One machine has a finite ceiling.'},
  {id: 'lb-13', kind: 'lb-screen', start: 97.53, end: 103.17, title: 'Architectural Pivot', subtitle: 'Rotate the scaling axis.', takeaway: 'The topology—not the node size—must change.'},
  {id: 'lb-14', kind: 'lb-screen', start: 103.63, end: 108.99, title: 'Bigger Becomes More', subtitle: 'Three machines create potential capacity.', takeaway: 'More capacity is not distributed traffic.'},
  {id: 'lb-15', kind: 'lb-screen', start: 109.59, end: 119.95, title: 'Server A, B, And C', subtitle: 'FoodDash creates a three-node application pool.', takeaway: 'Server B remains the legacy middle node.'},
  {id: 'lb-16', kind: 'lb-screen', start: 120.37, end: 126.01, title: 'Capacity Without Direction', subtitle: 'Three servers are ready, but routed load is zero.', takeaway: 'Capacity and utilization are different metrics.'},
  {id: 'lb-17', kind: 'lb-screen', start: 126.45, end: 132.57, title: 'A New Puzzle', subtitle: 'Request #001 has no destination.', takeaway: 'Every request needs a routing decision.'},
  {id: 'lb-18', kind: 'lb-screen', start: 132.81, end: 142.55, title: 'Which Server?', subtitle: 'A, B, and C are all healthy.', takeaway: 'Equivalent backends still need selection logic.'},
  {id: 'lb-19', kind: 'lb-screen', start: 142.95, end: 154.13, title: 'Power Without Direction', subtitle: 'The fleet is ready, but the front door is empty.', takeaway: 'Capacity and routing are separate concerns.'},
  {id: 'lb-20', kind: 'lb-screen', start: 154.55, end: 166.31, title: 'Three Empty Lanes', subtitle: 'Parallel capacity needs a dispatcher.', takeaway: 'Open lanes are useless without direction.'},
  {id: 'lb-21', kind: 'lb-screen', start: 166.77, end: 178.29, title: 'The Intelligent Front Door', subtitle: 'The load balancer enters the architecture.', takeaway: 'One component chooses backend destinations.'},
  {id: 'lb-22', kind: 'lb-screen', start: 178.71, end: 189.09, title: 'Intercept, Choose, Forward', subtitle: 'Generic forwarding uses B, A, then C.', takeaway: 'Selection exists before a specific policy is named.'},
  {id: 'lb-23', kind: 'lb-screen', start: 189.49, end: 198.87, title: 'Legacy Endpoint', subtitle: 'api.fooddash.com still targets Server B.', takeaway: 'The full spike follows the configured destination.'},
  {id: 'lb-24', kind: 'lb-screen', start: 199.21, end: 205.25, title: 'Split The Spike', subtitle: 'Three hundred requests become three batches of one hundred.', takeaway: 'The load balancer makes the fleet usable.'},
  {id: 'lb-25', kind: 'lb-screen', start: 205.65, end: 216.99, title: 'Scale Out', subtitle: 'Three servers process work in parallel.', takeaway: 'Horizontal scaling adds machines.'},
  {id: 'lb-26', kind: 'lb-screen', start: 217.33, end: 228.55, title: 'A Fleet Needs Routing', subtitle: 'Raw traffic must reach usable capacity.', takeaway: 'FoodDash uses a load balancer as its routing mechanism.'},
  {id: 'lb-27', kind: 'lb-screen', start: 229.01, end: 238.27, title: 'How Does It Choose?', subtitle: 'Topology gives way to routing policy.', takeaway: 'The front door needs a selection algorithm.'},
  {id: 'lb-28', kind: 'lb-screen', start: 238.61, end: 246.97, title: 'Many Strategies', subtitle: 'Start with the simplest intuition.', takeaway: 'Real load balancers support many policies.'},
  {id: 'lb-29', kind: 'lb-screen', start: 247.43, end: 256.35, title: 'Round Robin', subtitle: 'Request one goes to A, two to B, three to C.', takeaway: 'Successive requests follow a fixed cycle.'},
  {id: 'lb-30', kind: 'lb-screen', start: 256.57, end: 266.61, title: 'A, B, C — Repeat', subtitle: 'The selector wraps to the top.', takeaway: 'Round robin is simple and predictable.'},
  {id: 'lb-31', kind: 'lb-screen', start: 267.09, end: 274.59, title: 'More Than A Loop', subtitle: 'Modern balancers also protect availability.', takeaway: 'Routing policy can consume health state.'},
  {id: 'lb-32', kind: 'lb-screen', start: 274.95, end: 281.67, title: 'Integrate Health Checks', subtitle: 'The front door learns backend readiness.', takeaway: 'Only healthy servers should stay eligible.'},
  {id: 'lb-33', kind: 'lb-screen', start: 281.89, end: 287.51, title: 'Are You Healthy?', subtitle: 'Probes maintain the eligible backend set.', takeaway: 'Monitoring traffic is not user traffic.'},
  {id: 'lb-34', kind: 'lb-screen', start: 288.13, end: 294.81, title: 'Server B Crashes', subtitle: 'The process stops before the balancer knows.', takeaway: 'Health state is last-known state.'},
  {id: 'lb-35', kind: 'lb-screen', start: 294.95, end: 300.99, title: 'Detection Delay', subtitle: 'Missed probe, timeout, then unhealthy.', takeaway: 'Failure knowledge is earned through detection.'},
  {id: 'lb-36', kind: 'lb-screen', start: 301.09, end: 310.39, title: 'Withdraw And Reroute', subtitle: 'New requests go only to A and C.', takeaway: 'B is removed from rotation.'},
  {id: 'lb-37', kind: 'lb-screen', start: 310.61, end: 314.71, title: 'The Concepts Click', subtitle: 'Detect, decide, reroute.', takeaway: 'Monitoring and routing form one control loop.'},
  {id: 'lb-38', kind: 'lb-screen', start: 315.15, end: 321.37, title: 'Intelligence Then Action', subtitle: 'Health state changes the next route.', takeaway: 'Sensing and action are separate steps.'},
  {id: 'lb-39', kind: 'lb-screen', start: 321.85, end: 331.85, title: 'Automatic Resilience', subtitle: 'Traffic bypasses the failed server.', takeaway: 'No human step is needed.'},
  {id: 'lb-40', kind: 'lb-screen', start: 332.41, end: 339.03, title: 'One Front Door', subtitle: 'Every request now depends on one router.', takeaway: 'Centralized routing concentrates dependency.'},
  {id: 'lb-41', kind: 'lb-screen', start: 339.31, end: 344.23, title: 'What If This Fails?', subtitle: 'Turn the availability question around.', takeaway: 'The routing tier can be required too.'},
  {id: 'lb-42', kind: 'lb-screen', start: 344.51, end: 352.43, title: 'Healthy But Unreachable', subtitle: 'The pool waits behind a failed front door.', takeaway: 'Healthy components do not imply a reachable service.'},
  {id: 'lb-43', kind: 'lb-screen', start: 352.89, end: 360.21, title: 'A New SPOF', subtitle: 'One routing failure stops every request.', takeaway: 'The single deployment creates the vulnerability.'},
  {id: 'lb-44', kind: 'lb-screen', start: 360.93, end: 372.37, title: 'The Deployment Is Risky', subtitle: 'Load balancing is good; one load balancer is risky.', takeaway: 'The tool is not the problem—the topology is.'},
  {id: 'lb-45', kind: 'lb-screen', start: 372.95, end: 382.03, title: 'Apply Redundancy Again', subtitle: 'Duplicate the critical routing component.', takeaway: 'The front door needs a peer.'},
  {id: 'lb-46', kind: 'lb-screen', start: 382.37, end: 388.09, title: 'Redundant Load Balancers', subtitle: 'Primary and synchronized standby share one ingress.', takeaway: 'The routing tier becomes highly available.'},
  {id: 'lb-47', kind: 'lb-screen', start: 388.33, end: 394.75, title: 'Backup Takes Over', subtitle: 'The standby becomes active.', takeaway: 'Traffic continues through routing-tier failover.'},
  {id: 'lb-48', kind: 'lb-screen', start: 395.39, end: 400.27, title: 'Architecture Evolution', subtitle: 'Take a breath and review the system.', takeaway: 'Every topology change answered a concrete failure.'},
  {id: 'lb-49', kind: 'lb-screen', start: 400.77, end: 408.05, title: 'Capacity Then Routing', subtitle: 'One server became a pool, then gained a front door.', takeaway: 'Horizontal capacity creates a routing requirement.'},
  {id: 'lb-50', kind: 'lb-screen', start: 408.39, end: 416.25, title: 'Intelligence And Redundancy', subtitle: 'Health checks and a standby complete the design.', takeaway: 'The final system is scalable and resilient.'},
  {id: 'lb-51', kind: 'lb-screen', start: 416.75, end: 423.65, title: 'Built, Not Finished', subtitle: 'Routing policy still has deeper trade-offs.', takeaway: 'High availability does not settle assignment policy.'},
  {id: 'lb-52', kind: 'lb-screen', start: 424.07, end: 431.13, title: 'Unequal Capacity And Work', subtitle: 'A is larger; C is already busy.', takeaway: 'Equal request counts can create unequal pressure.'},
  {id: 'lb-53', kind: 'lb-screen', start: 431.39, end: 436.17, title: 'Equal Is Not Always Fair', subtitle: 'Backend latency can differ too.', takeaway: 'Efficient routing may need richer signals.'},
  {id: 'lb-54', kind: 'lb-screen', start: 436.39, end: 442.07, title: 'The Next Routing Puzzle', subtitle: 'Capacity, active load, and latency shape policy.', takeaway: 'Advanced routing is the next explainer.'},
  {id: 'lb-55', kind: 'lb-screen', start: 442.17, end: 444.79, title: 'Engineering Systems', subtitle: 'Thanks for watching.', takeaway: 'Keep building great systems.'},
];
