import type {LessonBeat} from '../../types';

export const lessonPlan: LessonBeat[] = [
  {
    id: 'intro',
    kind: 'availability-intro',
    start: 0,
    end: 8.92,
    title: 'Engineering Systems',
    subtitle: 'Availability Patterns #1',
    takeaway: 'A new series about systems that keep serving users.',
  },
  {
    id: 'consistency-recap',
    kind: 'availability-series-shift',
    start: 8.92,
    end: 17.62,
    title: 'From Consistency',
    subtitle: 'Correct data across many nodes.',
    takeaway: 'The last series asked what users should see.',
  },
  {
    id: 'accuracy-recap',
    kind: 'availability-series-shift',
    start: 17.62,
    end: 27.58,
    title: 'To Availability',
    subtitle: 'Can users reach the system at all?',
    takeaway: 'Correct data does not help if the service is unreachable.',
  },
  {
    id: 'survives-world',
    kind: 'availability-pillar',
    start: 27.58,
    end: 34.98,
    title: 'Survive The Real World',
    subtitle: 'Availability is where architecture meets failure.',
    takeaway: 'This is the pillar that keeps products alive.',
  },
  {
    id: 'roadmap-one',
    kind: 'availability-roadmap',
    start: 34.98,
    end: 42.82,
    title: 'Today\'s Roadmap',
    subtitle: 'Consistency vs availability, then reachability.',
    takeaway: 'Start with the core contrast and definition.',
  },
  {
    id: 'roadmap-two',
    kind: 'availability-roadmap',
    start: 42.82,
    end: 51.86,
    title: 'Today\'s Roadmap',
    subtitle: 'Downtime, failure, patterns, and single points.',
    takeaway: 'Then connect the ideas to real architecture.',
  },
  {
    id: 'section-one',
    kind: 'consistency-vs-availability',
    start: 51.86,
    end: 60.48,
    title: 'Two Pillars',
    subtitle: 'Correct data versus reachable service.',
    takeaway: 'Distributed systems need both dimensions.',
  },
  {
    id: 'consistency-side',
    kind: 'consistency-side',
    start: 60.48,
    end: 69.44,
    title: 'Consistency',
    subtitle: 'Every replica agrees on the correct data.',
    takeaway: 'Consistency protects what users see.',
  },
  {
    id: 'catch',
    kind: 'availability-catch',
    start: 69.44,
    end: 79.56,
    title: 'The Catch',
    subtitle: 'Perfect correctness is useless if users cannot reach it.',
    takeaway: 'Reachability is a first-class system property.',
  },
  {
    id: 'availability-side',
    kind: 'availability-side',
    start: 79.56,
    end: 88.82,
    title: 'Availability',
    subtitle: 'Can users access the system when they need it?',
    takeaway: 'Availability focuses on successful access.',
  },
  {
    id: 'definition-question',
    kind: 'availability-definition',
    start: 88.82,
    end: 99.4,
    title: 'What Is Availability?',
    subtitle: 'The ability to successfully respond to user requests.',
    takeaway: 'For one interaction, available means a correct response arrives.',
  },
  {
    id: 'single-interaction',
    kind: 'request-response',
    start: 99.4,
    end: 106.62,
    title: 'Single Request',
    subtitle: 'Request goes out. Response comes back.',
    takeaway: 'That interaction counts as available.',
  },
  {
    id: 'unavailable',
    kind: 'timeout-unavailable',
    start: 106.62,
    end: 116.28,
    title: 'Unavailable',
    subtitle: 'Error, timeout, or no useful response.',
    takeaway: 'Simple per request; harder across millions of requests.',
  },
  {
    id: 'scale-measurement',
    kind: 'availability-at-scale',
    start: 116.28,
    end: 124.36,
    title: 'Measure At Scale',
    subtitle: 'Availability is tracked as percentages, or nines.',
    takeaway: 'Tiny decimals change the engineering reality.',
  },
  {
    id: 'two-nines',
    kind: 'nines-table',
    start: 124.36,
    end: 131.34,
    title: 'Two Nines',
    subtitle: '99% can still allow days of downtime.',
    takeaway: 'A high-looking percentage can hide a lot of outage time.',
  },
  {
    id: 'three-nines',
    kind: 'nines-shrink',
    start: 131.34,
    end: 137.54,
    title: 'Three Nines',
    subtitle: '99.9% shrinks downtime to hours.',
    takeaway: 'One extra nine tightens the reliability budget.',
  },
  {
    id: 'four-nines',
    kind: 'nines-shrink',
    start: 137.54,
    end: 142.58,
    title: 'Four Nines',
    subtitle: '99.99% means minutes, not days.',
    takeaway: 'The budget keeps shrinking fast.',
  },
  {
    id: 'five-nines',
    kind: 'nines-shrink',
    start: 142.58,
    end: 154.42,
    title: 'Five Nines',
    subtitle: '99.999% leaves only a few minutes per year.',
    takeaway: 'That extra decimal becomes an engineering challenge.',
  },
  {
    id: 'fooddash-setup',
    kind: 'fooddash-map',
    start: 154.42,
    end: 163.8,
    title: 'Real-World Cost',
    subtitle: 'A fictional food delivery platform: FoodDash.',
    takeaway: 'Downtime becomes concrete when users are in the flow.',
  },
  {
    id: 'dinner-rush',
    kind: 'fooddash-rush',
    start: 163.8,
    end: 171.3,
    title: 'Dinner Rush',
    subtitle: '8pm peak traffic is hitting hard.',
    takeaway: 'Availability pressure spikes exactly when demand spikes.',
  },
  {
    id: 'user-journey',
    kind: 'fooddash-journey',
    start: 171.3,
    end: 181.32,
    title: 'Ordering Flow',
    subtitle: 'Open app, browse, cart, place order.',
    takeaway: 'Millions of users depend on one visible workflow.',
  },
  {
    id: 'critical-server-fails',
    kind: 'outage-blast',
    start: 181.32,
    end: 189.58,
    title: 'Critical Failure',
    subtitle: 'A server fails at the worst possible moment.',
    takeaway: 'Availability incidents often land during peak pressure.',
  },
  {
    id: 'ten-minute-outage',
    kind: 'service-unavailable',
    start: 189.58,
    end: 195.74,
    title: 'Service Unavailable',
    subtitle: 'A 10-minute outage is not small.',
    takeaway: 'The blast radius is business, not just servers.',
  },
  {
    id: 'customer-impact',
    kind: 'outage-impact',
    start: 195.74,
    end: 203.72,
    title: 'Outage Fallout',
    subtitle: 'Customers leave, kitchens idle, partners wait.',
    takeaway: 'Every dependent actor feels the failure.',
  },
  {
    id: 'revenue-trust',
    kind: 'business-concern',
    start: 203.72,
    end: 210.16,
    title: 'Business Concern',
    subtitle: 'Revenue falls and customer trust breaks.',
    takeaway: 'Availability is a product and business requirement.',
  },
  {
    id: 'availability-business-metric',
    kind: 'business-concern',
    start: 210.16,
    end: 216.36,
    title: 'Not Just A Metric',
    subtitle: 'Availability is not only a dashboard percentage.',
    takeaway: 'It is a critical business concern.',
  },
  {
    id: 'cost-summary',
    kind: 'downtime-cost',
    start: 216.36,
    end: 224.1,
    title: 'Wrong Time, Huge Cost',
    subtitle: 'Ten minutes can cost millions.',
    takeaway: 'Timing and traffic decide the real damage.',
  },
  {
    id: 'failure-question',
    kind: 'failure-question',
    start: 224.1,
    end: 233.04,
    title: 'Can We Hit 100%?',
    subtitle: 'Can service unavailable literally never happen?',
    takeaway: 'The honest answer shapes the architecture.',
  },
  {
    id: 'failure-question-guarantee',
    kind: 'failure-question',
    start: 233.04,
    end: 237,
    title: '100% Availability?',
    subtitle: 'Can we guarantee it forever?',
    takeaway: 'This is the limit every design runs into.',
  },
  {
    id: 'impossible',
    kind: 'reality-breaks',
    start: 237,
    end: 245.68,
    title: 'Almost Impossible',
    subtitle: 'Theory sounds clean; practice runs on physical reality.',
    takeaway: 'Physical reality breaks.',
  },
  {
    id: 'practice-breaks',
    kind: 'reality-breaks',
    start: 245.68,
    end: 249.76,
    title: 'Practice Breaks',
    subtitle: 'Distributed systems run on physical reality.',
    takeaway: 'That reality is why availability engineering exists.',
  },
  {
    id: 'hardware-breaks',
    kind: 'failure-list',
    start: 249.76,
    end: 259.6,
    title: 'Things Break',
    subtitle: 'Hardware, drives, cables, and power.',
    takeaway: 'Infrastructure has failure modes everywhere.',
  },
  {
    id: 'cloud-software-breaks',
    kind: 'failure-list',
    start: 259.6,
    end: 269.38,
    title: 'More Things Break',
    subtitle: 'Cloud regions, software bugs, deployments.',
    takeaway: 'Even managed platforms and human workflows fail.',
  },
  {
    id: 'failure-expected',
    kind: 'failure-expected',
    start: 269.38,
    end: 280.02,
    title: 'Expected, Not Exceptional',
    subtitle: 'Modern engineers stop asking how to prevent every failure.',
    takeaway: 'Failure is part of the operating model.',
  },
  {
    id: 'mindset-shift',
    kind: 'availability-mindset',
    start: 280.02,
    end: 287.9,
    title: 'Availability Mindset',
    subtitle: 'How do we keep working when failures occur?',
    takeaway: 'That question is the foundation.',
  },
  {
    id: 'patterns-section',
    kind: 'patterns-toolkit',
    start: 287.9,
    end: 298.38,
    title: 'Availability Patterns',
    subtitle: 'Designing for resilience.',
    takeaway: 'Patterns are the architectural toolkit.',
  },
  {
    id: 'patterns-purpose',
    kind: 'patterns-purpose',
    start: 298.38,
    end: 306.98,
    title: 'Remain Operational',
    subtitle: 'Serve users despite failed parts.',
    takeaway: 'The system can survive local component failure.',
  },
  {
    id: 'redundancy',
    kind: 'redundancy-pattern',
    start: 306.98,
    end: 310.26,
    title: 'Redundancy',
    subtitle: 'Run multiple servers instead of one.',
    takeaway: 'Capacity and backup paths start with duplication.',
  },
  {
    id: 'pattern-grid-one',
    kind: 'pattern-grid',
    start: 310.26,
    end: 318.2,
    title: 'Pattern Toolkit',
    subtitle: 'Replication, failover, and load balancing.',
    takeaway: 'Route around failed capacity.',
  },
  {
    id: 'pattern-grid-two',
    kind: 'failure-isolation',
    start: 318.2,
    end: 327.62,
    title: 'Pattern Toolkit',
    subtitle: 'Automatic recovery and failure isolation.',
    takeaway: 'Keep one broken service from taking down the platform.',
  },
  {
    id: 'before-fix',
    kind: 'spof-intro',
    start: 327.62,
    end: 335.98,
    title: 'How Systems Break',
    subtitle: 'Before fixing availability, identify failure shape.',
    takeaway: 'Single points of failure are the first enemy.',
  },
  {
    id: 'fooddash-one-server',
    kind: 'single-server',
    start: 335.98,
    end: 343.84,
    title: 'One Big Server',
    subtitle: 'FoodDash runs the whole platform on one machine.',
    takeaway: 'Powerful is not the same as resilient.',
  },
  {
    id: 'server-crash',
    kind: 'crash-offline',
    start: 343.84,
    end: 352.74,
    title: 'One Crash',
    subtitle: 'The server goes down. The business goes offline.',
    takeaway: 'One failed component can stop every user flow.',
  },
  {
    id: 'spof-definition',
    kind: 'spof-definition',
    start: 352.74,
    end: 358.08,
    title: 'Single Point Of Failure',
    subtitle: 'A component whose failure brings down the entire system.',
    takeaway: 'That component owns too much blast radius.',
  },
  {
    id: 'remove-spof',
    kind: 'remove-spof',
    start: 358.08,
    end: 364.06,
    title: 'First Step',
    subtitle: 'Identify and remove single points of failure.',
    takeaway: 'High availability starts by shrinking blast radius.',
  },
  {
    id: 'avoid-failure',
    kind: 'catastrophe-goal',
    start: 364.06,
    end: 373.26,
    title: 'The Real Goal',
    subtitle: 'Not avoiding all failure. Avoid catastrophic failure.',
    takeaway: 'The product should survive broken parts.',
  },
  {
    id: 'user-never-notices',
    kind: 'user-never-notices',
    start: 373.26,
    end: 380.48,
    title: 'Never Notices',
    subtitle: 'Dinner still gets ordered when a server fails.',
    takeaway: 'User impact is the availability test.',
  },
  {
    id: 'recap-one',
    kind: 'recap-availability',
    start: 380.48,
    end: 388.5,
    title: 'Quick Recap',
    subtitle: 'Reachability, downtime cost, inevitable failure, patterns, SPOFs.',
    takeaway: 'Availability is how systems keep serving through failure.',
  },
  {
    id: 'recap-two',
    kind: 'recap-availability',
    start: 388.5,
    end: 396.04,
    title: 'Quick Recap',
    subtitle: 'Patterns help systems survive broken parts.',
    takeaway: 'Single points of failure are the first danger to remove.',
  },
  {
    id: 'foundation',
    kind: 'next-spof',
    start: 396.04,
    end: 401.26,
    title: 'Series Foundation',
    subtitle: 'Next: a deep dive into single points of failure.',
    takeaway: 'First understand what brings systems down.',
  },
  {
    id: 'next-deep-dive',
    kind: 'next-spof',
    start: 401.26,
    end: 410.98,
    title: 'Next Time',
    subtitle: 'Single points of failure.',
    takeaway: 'Understand what brings systems down before building high availability.',
  },
  {
    id: 'final-question',
    kind: 'final-question',
    start: 410.98,
    end: 414.06,
    title: 'Final Thought',
    subtitle: 'If your system failed right now, who would know?',
    takeaway: 'Design availability from user-visible impact.',
  },
  {
    id: 'closing',
    kind: 'closing',
    start: 414.06,
    end: 424.08,
    title: 'Thanks For Watching',
    subtitle: 'Engineering Systems',
    takeaway: 'End of Availability Patterns #1.',
  },
];
