import type {LessonBeat} from '../../types';

export const lessonPlan: LessonBeat[] = [
  {id: 'l47-01', kind: 'l47-screen', start: 0.07, end: 6.29, title: 'Welcome', subtitle: 'Layer 4 vs Layer 7 Load Balancing', takeaway: 'The episode explains how much a load balancer should understand.'},
  {id: 'l47-02', kind: 'l47-screen', start: 6.29, end: 14.07, title: 'Previous Lesson', subtitle: 'A load balancer still needs the right policy', takeaway: 'Distribution policy affects performance and reliability.'},
  {id: 'l47-03', kind: 'l47-screen', start: 14.07, end: 23.61, title: 'Requests Look Balanced', subtitle: 'The algorithm spreads traffic evenly', takeaway: 'FoodDash starts from a healthy-looking backend pool.'},
  {id: 'l47-04', kind: 'l47-screen', start: 24.65, end: 34.07, title: 'New Requirement', subtitle: 'FoodDash is growing into many product surfaces', takeaway: 'Growth changes the routing problem.'},
  {id: 'l47-05', kind: 'l47-screen', start: 34.07, end: 44.49, title: 'Four Audiences', subtitle: 'Customers, restaurants, drivers, and admins need different portals', takeaway: 'One product now has multiple destinations.'},
  {id: 'l47-06', kind: 'l47-screen', start: 45.23, end: 54.59, title: 'Independent Services', subtitle: 'The team wants separate backend services', takeaway: 'A load balancer alone does not answer where each request belongs.'},
  {id: 'l47-07', kind: 'l47-screen', start: 54.59, end: 62.97, title: 'Routing Question', subtitle: 'Which service should receive this request?', takeaway: 'The balancer must choose a destination, not just a server.'},
  {id: 'l47-08', kind: 'l47-screen', start: 62.97, end: 72.79, title: 'Two Approaches', subtitle: 'The OSI model names the split', takeaway: 'Layer 4 and Layer 7 describe different levels of understanding.'},
  {id: 'l47-09', kind: 'l47-screen', start: 72.79, end: 80.77, title: 'Layer 4', subtitle: 'Transport-layer load balancing', takeaway: 'Layer 4 routes using network-level information.'},
  {id: 'l47-10', kind: 'l47-screen', start: 80.77, end: 89.47, title: 'Network Signals', subtitle: 'IP addresses, ports, TCP, and UDP', takeaway: 'Layer 4 can be fast because the inspection is shallow.'},
  {id: 'l47-11', kind: 'l47-screen', start: 89.47, end: 99.77, title: 'What L4 Cannot See', subtitle: 'No URL, no HTTP intent, no product area', takeaway: 'Layer 4 does not open the HTTP request.'},
  {id: 'l47-12', kind: 'l47-screen', start: 99.77, end: 110.03, title: 'Courier Analogy', subtitle: 'Sort by shipping label without opening the box', takeaway: 'Layer 4 knows source and destination, not contents.'},
  {id: 'l47-13', kind: 'l47-screen', start: 110.03, end: 120.91, title: 'Fast Path', subtitle: 'Very little inspection means very high speed', takeaway: 'Layer 4 is excellent when all backends perform the same job.'},
  {id: 'l47-14', kind: 'l47-screen', start: 120.91, end: 127.49, title: 'Production Scale', subtitle: 'FoodDash is growing beyond startup fragility', takeaway: 'Every episode adds one more production constraint.'},
  {id: 'l47-15', kind: 'l47-screen', start: 127.49, end: 133.23, title: 'Series Bridge', subtitle: 'Every episode builds on the last one', takeaway: 'The next constraint is smarter routing.'},
  {id: 'l47-16', kind: 'l47-screen', start: 133.23, end: 142.79, title: 'Make It Smarter', subtitle: 'Same domain, different user journeys', takeaway: 'Now routing needs application context.'},
  {id: 'l47-17', kind: 'l47-screen', start: 142.79, end: 153.39, title: 'Same Domain', subtitle: 'Root, restaurant, and driver paths should split', takeaway: 'Different URLs can represent different backend services.'},
  {id: 'l47-18', kind: 'l47-screen', start: 153.39, end: 162.21, title: 'Layer 4 Limit', subtitle: 'The transport balancer cannot make path-based choices', takeaway: 'If it never looks inside, it cannot route by application intent.'},
  {id: 'l47-19', kind: 'l47-screen', start: 162.21, end: 169.99, title: 'Layer 7', subtitle: 'Application-layer load balancing', takeaway: 'Layer 7 understands the request itself.'},
  {id: 'l47-20', kind: 'l47-screen', start: 169.99, end: 179.45, title: 'Application Signals', subtitle: 'URLs, headers, cookies, host names, methods', takeaway: 'Layer 7 can inspect rich HTTP context.'},
  {id: 'l47-21', kind: 'l47-screen', start: 179.45, end: 190.77, title: 'Path Routing', subtitle: 'Restaurant, driver, and API requests split cleanly', takeaway: 'Layer 7 routes by application meaning.'},
  {id: 'l47-22', kind: 'l47-screen', start: 190.77, end: 199.77, title: 'One App Outside', subtitle: 'Many services behind the scenes', takeaway: 'Users see one application while the edge routes intelligently.'},
  {id: 'l47-23', kind: 'l47-screen', start: 200.39, end: 209.85, title: 'Is L7 Better?', subtitle: 'Not automatically', takeaway: 'Smarter does not always mean better.'},
  {id: 'l47-24', kind: 'l47-screen', start: 209.85, end: 219.59, title: 'Speed vs Flexibility', subtitle: 'Layer 4 does less; Layer 7 understands more', takeaway: 'The extra intelligence has processing cost.'},
  {id: 'l47-25', kind: 'l47-screen', start: 219.59, end: 229.55, title: 'Different Problems', subtitle: 'Neither approach wins universally', takeaway: 'Choose the layer based on the engineering problem.'},
  {id: 'l47-26', kind: 'l47-screen', start: 229.55, end: 239.55, title: 'Engineering Rule', subtitle: 'Do not choose the most advanced solution by default', takeaway: 'Good engineering chooses the right solution for the problem.'},
  {id: 'l47-27', kind: 'l47-screen', start: 239.55, end: 249.97, title: 'FoodDash Stack', subtitle: 'Redundancy, health checks, failover, load balancing, routing', takeaway: 'The system has become much more resilient.'},
  {id: 'l47-28', kind: 'l47-screen', start: 249.97, end: 260.39, title: 'Still A Limit', subtitle: 'Even smart routing cannot solve every failure', takeaway: 'A failed server is not the same as a failed location.'},
  {id: 'l47-29', kind: 'l47-screen', start: 260.39, end: 270.87, title: 'Next Failure', subtitle: 'What if an entire data center goes offline?', takeaway: 'The next scale boundary is the availability zone.'},
  {id: 'l47-30', kind: 'l47-screen', start: 270.87, end: 275.97, title: 'Next Episode', subtitle: 'FoodDash enters multi-AZ architecture', takeaway: 'The story moves from smart routing to location-level resilience.'},
  {id: 'l47-31', kind: 'closing', start: 276.53, end: 283.45, title: 'Engineering Systems Closing', subtitle: 'Thanks for watching', takeaway: 'Keep building great systems.'},
];
