import type {LessonBeat} from '../../types';

export const lessonPlan: LessonBeat[] = [
  {id: 'rr-01', kind: 'rr-screen', start: 0, end: 6, title: 'Engineering Systems', subtitle: 'Engineering Systems', takeaway: 'Small system diagram sketch animates in.'},
  {id: 'rr-02', kind: 'rr-screen', start: 6, end: 15, title: 'Previously: Single Point of Failure', subtitle: 'Mobile App -> Web Servers -> Single Database', takeaway: 'Database pulses red.'},
  {id: 'rr-03', kind: 'rr-screen', start: 15, end: 24, title: 'One Database Failed', subtitle: 'App and web stayed green; the database crashed.', takeaway: 'Traffic lines break and user flows fade out.'},
  {id: 'rr-04', kind: 'rr-screen', start: 24, end: 30, title: 'Classic SPOF', subtitle: 'One component owned the whole blast radius.', takeaway: 'Warning marker locks onto the database.'},
  {id: 'rr-05', kind: 'rr-screen', start: 30, end: 38, title: 'How do we remove it?', subtitle: 'The next challenge after finding a SPOF.', takeaway: 'Engineer marks the failed database with a question.'},
  {id: 'rr-06', kind: 'rr-screen', start: 38, end: 49.26, title: 'How do they handle failures?', subtitle: 'Amazon, Netflix, Uber, Google keep users online while parts fail.', takeaway: 'User traffic continues through healthy paths.'},
  {id: 'rr-06b', kind: 'rr-screen', start: 49.26, end: 55.16, title: 'Failure is guaranteed', subtitle: 'In distributed systems, failure is not a possibility.', takeaway: 'It is an absolute guarantee.'},
  {id: 'rr-07', kind: 'rr-screen', start: 55.16, end: 62.58, title: 'The Answer Begins Here', subtitle: 'Two fundamental availability concepts.', takeaway: 'Redundancy and replication.'},
  {id: 'rr-08', kind: 'rr-screen', start: 62.58, end: 70.1, title: 'Roadmap', subtitle: 'FoodDash Outage -> Redundancy & Replication', takeaway: 'First, revisit the outage and the foundational concepts.'},
  {id: 'rr-08b', kind: 'rr-screen', start: 70.1, end: 79.68, title: 'Roadmap', subtitle: 'Active-Passive -> Active-Active -> Trade-Off', takeaway: 'Then compare failover models and their trade-offs.'},
  {id: 'rr-09', kind: 'rr-screen', start: 79.68, end: 82, title: 'Part 1', subtitle: 'FoodDash Outage', takeaway: 'Investigating the Breakdown'},
  {id: 'rr-10', kind: 'rr-screen', start: 82, end: 91.68, title: 'Not everything failed', subtitle: 'App, web, and payment stayed green. Database failed.', takeaway: 'Only database blinks red.'},
  {id: 'rr-11', kind: 'rr-screen', start: 91.68, end: 97.44, title: 'One database server failed', subtitle: 'The root cause was simpler and more fragile.', takeaway: 'The single database becomes the spotlight.'},
  {id: 'rr-11b', kind: 'rr-screen', start: 97.44, end: 105.56, title: 'Everything depended on one box', subtitle: 'Orders, payments, login, restaurant updates', takeaway: 'Dependency arrows converge on the database.'},
  {id: 'rr-12', kind: 'rr-screen', start: 105.56, end: 110, title: 'Blast Radius: Total', subtitle: 'Database failure spreads outward.', takeaway: 'All dependent flows turn red.'},
  {id: 'rr-13', kind: 'rr-screen', start: 110, end: 118, title: 'What if we had another database?', subtitle: 'Post-mortem question', takeaway: 'Second database sketch appears.'},
  {id: 'rr-14', kind: 'rr-screen', start: 118, end: 123, title: 'Part 2', subtitle: 'Redundancy & Replication', takeaway: 'The Foundation'},
  {id: 'rr-15', kind: 'rr-screen', start: 123, end: 134, title: 'Redundancy = Extra Components', subtitle: 'One database becomes two. One server becomes a fleet.', takeaway: 'Backup icons appear beside originals.'},
  {id: 'rr-16', kind: 'rr-screen', start: 134, end: 144, title: 'More than one way to survive', subtitle: '2 Databases / Server Fleet / Redundant Storage / Alternate Network Path', takeaway: 'Each example animates exactly when it is spoken.'},
  {id: 'rr-17', kind: 'rr-screen', start: 144, end: 149, title: 'Remove dependency on one machine', subtitle: 'Single path breaks into multiple paths.', takeaway: 'Green paths replace the red dependency.'},
  {id: 'rr-18', kind: 'rr-screen', start: 149, end: 158, title: 'Extra hardware is not enough', subtitle: 'Second database appears shiny, then warns.', takeaway: 'Warning icon appears on backup.'},
  {id: 'rr-19', kind: 'rr-screen', start: 158, end: 164, title: 'Two databases. One has data.', subtitle: 'Primary full. Secondary empty.', takeaway: 'Backup opens as an empty box.'},
  {id: 'rr-20', kind: 'rr-screen', start: 164, end: 174.7, title: 'Empty backup = useless backup', subtitle: 'No Orders / No Menus / No Deliveries', takeaway: 'Missing evidence appears one question at a time.'},
  {id: 'rr-21', kind: 'rr-screen', start: 174.7, end: 180.36, title: 'No data. No recovery.', subtitle: 'Primary fails. Traffic hits empty backup.', takeaway: 'User request fails against an empty shell.'},
  {id: 'rr-22', kind: 'rr-screen', start: 180.36, end: 190, title: 'Replication = Synchronized Copies', subtitle: 'Orders, menus, payments, deliveries flow across.', takeaway: 'The answer is revealed only after the empty-shell problem.'},
  {id: 'rr-23', kind: 'rr-screen', start: 190, end: 201, title: 'Hardware + Data', subtitle: 'Redundancy adds machines. Replication copies state.', takeaway: 'Right side fills with copied records.'},
  {id: 'rr-24', kind: 'rr-screen', start: 201, end: 211, title: 'They work together', subtitle: 'Redundancy needs replication; replication needs redundancy.', takeaway: 'Connector line joins the cards.'},
  {id: 'rr-25', kind: 'rr-screen', start: 211, end: 219, title: 'Redundancy adds seats. Replication fills them.', subtitle: 'Doodle bus analogy', takeaway: 'Data icons sit in empty seats.'},
  {id: 'rr-26', kind: 'rr-screen', start: 219, end: 230.5, title: 'Primary handles traffic. Secondary receives copies.', subtitle: 'App -> Web Server -> Primary DB; Primary DB -> Secondary DB', takeaway: 'Traffic and replication move on separate paths.'},
  {id: 'rr-27', kind: 'rr-screen', start: 230.5, end: 239, title: 'Important data now exists twice', subtitle: 'Orders, payments, restaurant info', takeaway: 'Same records appear in both databases.'},
  {id: 'rr-28', kind: 'rr-screen', start: 239, end: 245, title: 'A copy exists. The business survives.', subtitle: 'Primary fails, secondary stays green.', takeaway: 'FoodDash remains online.'},
  {id: 'rr-29', kind: 'rr-screen', start: 245, end: 252, title: 'Part 3', subtitle: 'Active-Passive', takeaway: 'Simple Failover'},
  {id: 'rr-30', kind: 'rr-screen', start: 252, end: 258, title: 'One active. One standby.', subtitle: 'Active DB green, passive DB ready.', takeaway: 'Replication arrow runs in background.'},
  {id: 'rr-31', kind: 'rr-screen', start: 258, end: 265, title: 'Active handles production traffic', subtitle: 'Users, restaurants, drivers route to active.', takeaway: 'Passive remains visible and idle.'},
  {id: 'rr-32', kind: 'rr-screen', start: 265, end: 274, title: 'Passive stays synced', subtitle: 'Active sends updates to passive.', takeaway: 'Passive fills with same records.'},
  {id: 'rr-33', kind: 'rr-screen', start: 274, end: 278, title: 'Active fails', subtitle: 'Failure counter: 1 Failure', takeaway: 'Traffic line stops.'},
  {id: 'rr-34', kind: 'rr-screen', start: 278, end: 282, title: 'Passive -> Active', subtitle: 'Standby is promoted.', takeaway: 'Label flips to New Active.'},
  {id: 'rr-35', kind: 'rr-screen', start: 282, end: 286, title: 'Traffic redirected', subtitle: 'Requests resume through promoted DB.', takeaway: 'Rerouting arrow curves around failure.'},
  {id: 'rr-36', kind: 'rr-screen', start: 286, end: 291, title: 'Clear primary. Clear backup.', subtitle: 'Simple two-step failover', takeaway: 'Checkmark appears.'},
  {id: 'rr-37', kind: 'rr-screen', start: 291, end: 299, title: 'Idle infrastructure', subtitle: 'Passive waits with clock and cost meter.', takeaway: 'Cost continues increasing.'},
  {id: 'rr-38', kind: 'rr-screen', start: 299, end: 307.78, title: 'Paid capacity. Zero daily traffic.', subtitle: 'Active busy. Passive at 0 requests.', takeaway: 'Counters show wasted capacity.'},
  {id: 'rr-39', kind: 'rr-screen', start: 307.78, end: 312.86, title: 'Useful in failure. Idle otherwise.', subtitle: 'Spare tire analogy', takeaway: 'Paid capacity occupies space.'},
  {id: 'rr-40', kind: 'rr-screen', start: 312.86, end: 314.96, title: 'What is the alternative?', subtitle: 'Standby wakes up.', takeaway: 'Passive starts turning green.'},
  {id: 'rr-41', kind: 'rr-screen', start: 314.96, end: 319.98, title: 'Part 4', subtitle: 'Active-Active', takeaway: 'Simultaneous Capacity'},
  {id: 'rr-42', kind: 'rr-screen', start: 319.98, end: 329.24, title: 'Both are active', subtitle: 'DB A and DB B both participate.', takeaway: 'Both receive active badges.'},
  {id: 'rr-43', kind: 'rr-screen', start: 329.24, end: 336.04, title: 'Both serve production traffic', subtitle: 'User traffic splits 50/50.', takeaway: 'Counters rise on both databases.'},
  {id: 'rr-44', kind: 'rr-screen', start: 336.04, end: 342.16, title: 'One fails. One continues.', subtitle: 'DB A fails, DB B stays green.', takeaway: 'DB B counter speeds up.'},
  {id: 'rr-45', kind: 'rr-screen', start: 342.16, end: 345.6, title: 'Remaining capacity absorbs load', subtitle: 'Traffic bends toward DB B.', takeaway: 'Load meter rises but stays green.'},
  {id: 'rr-46', kind: 'rr-screen', start: 345.6, end: 350, title: 'More capacity. More availability.', subtitle: 'Better utilization / Higher availability / More scalability', takeaway: 'Benefit cards pop in.'},
  {id: 'rr-47', kind: 'rr-screen', start: 350, end: 357, title: 'Part 5', subtitle: 'Availability Trade-Off', takeaway: 'Complexity vs Uptime'},
  {id: 'rr-48', kind: 'rr-screen', start: 357, end: 363, title: 'Two designs. Different trade-offs.', subtitle: 'Active-Passive vs Active-Active', takeaway: 'Simple arrow versus split traffic.'},
  {id: 'rr-49', kind: 'rr-screen', start: 363, end: 368, title: 'Simple failover. Fewer sync headaches.', subtitle: 'Active-passive advantages', takeaway: 'One clean replication arrow.'},
  {id: 'rr-50', kind: 'rr-screen', start: 368, end: 376, title: 'Higher scale. Harder sync.', subtitle: 'Active-active accepts writes on both sides.', takeaway: 'Warning appears between databases.'},
  {id: 'rr-51', kind: 'rr-screen', start: 376, end: 385, title: 'Conflicts can happen', subtitle: 'Two writes touch the same order.', takeaway: 'Conflict warning flashes.'},
  {id: 'rr-52', kind: 'rr-screen', start: 385, end: 388, title: 'Coordination complexity rises', subtitle: 'Sync arrows multiply.', takeaway: 'Warning icons surround sync lines.'},
  {id: 'rr-53', kind: 'rr-screen', start: 388, end: 400, title: 'No free lunch', subtitle: 'Resilience and engineering effort rise together.', takeaway: 'Balance scale shifts.'},
  {id: 'rr-54', kind: 'rr-screen', start: 400, end: 405, title: 'Internal apps: Active-Passive often works', subtitle: 'Small office app, low complexity.', takeaway: 'Failover checkmark appears.'},
  {id: 'rr-55', kind: 'rr-screen', start: 405, end: 413, title: 'Massive scale needs Active-Active', subtitle: 'Millions of user dots flood both active databases.', takeaway: 'Scale meter rises.'},
  {id: 'rr-56', kind: 'rr-screen', start: 413, end: 418.26, title: 'Architecture depends on context', subtitle: 'Requirements / Expertise / Budget', takeaway: 'Factors light up as spoken.'},
  {id: 'rr-57', kind: 'rr-screen', start: 418.26, end: 422, title: 'Quick Recap', subtitle: 'Timeline rewinds from trade-off to SPOF.', takeaway: 'Recap mode starts.'},
  {id: 'rr-58', kind: 'rr-screen', start: 422, end: 424, title: 'SPOFs create massive outages', subtitle: 'Single database failure dims the system.', takeaway: 'Whole system goes red.'},
  {id: 'rr-59', kind: 'rr-screen', start: 424, end: 428, title: 'Redundancy removes single dependency', subtitle: 'One database becomes two.', takeaway: 'Multiple paths appear.'},
  {id: 'rr-60', kind: 'rr-screen', start: 428, end: 431, title: 'Replication protects data', subtitle: 'Primary copies to secondary.', takeaway: 'Secondary fills.'},
  {id: 'rr-61', kind: 'rr-screen', start: 431, end: 434, title: 'Active-Passive = Simple failover', subtitle: 'Passive promoted to active.', takeaway: 'A clean failover path.'},
  {id: 'rr-62', kind: 'rr-screen', start: 434, end: 438, title: 'Active-Active = Availability + Scale', subtitle: 'Traffic splits across active systems.', takeaway: 'Both counters increase.'},
  {id: 'rr-63', kind: 'rr-screen', start: 438, end: 443, title: 'Highly Available Systems', subtitle: 'Redundancy / Replication / Active-Passive / Active-Active', takeaway: 'Principles combine into availability.'},
  {id: 'rr-64', kind: 'rr-screen', start: 443, end: 463, title: 'But one piece is missing...', subtitle: 'Detection turns backups into automatic recovery.', takeaway: 'The missing detection layer appears.'},
  {id: 'rr-70', kind: 'closing', start: 463, end: 478.04, title: 'Engineering Systems', subtitle: 'Final redundant FoodDash architecture', takeaway: 'Health-check pulse fades into outro.'},
];
