import type {LessonBeat} from '../../types';

export const lessonPlan: LessonBeat[] = [
  {id: 'maz-01', kind: 'maz-screen', start: 0, end: 3.73, title: 'Three App Servers', subtitle: 'FoodDash has a backend pool.', takeaway: 'The architecture starts with server-level redundancy.'},
  {id: 'maz-02', kind: 'maz-screen', start: 3.73, end: 7.59, title: 'Load Balancer', subtitle: 'Requests are distributed between servers.', takeaway: 'Traffic has a front door and multiple destinations.'},
  {id: 'maz-03', kind: 'maz-screen', start: 7.59, end: 13.35, title: 'One Server Fails', subtitle: 'The other two servers keep handling requests.', takeaway: 'Server-level failure can be survived.'},
  {id: 'maz-04', kind: 'maz-screen', start: 13.35, end: 16.89, title: 'Highly Available?', subtitle: 'The architecture looks solved.', takeaway: 'At first glance, the system seems resilient.'},
  {id: 'maz-05', kind: 'maz-screen', start: 16.89, end: 23.01, title: 'Same Building', subtitle: 'A hidden physical boundary appears.', takeaway: 'Redundant servers can still share one location.'},
  {id: 'maz-06', kind: 'maz-screen', start: 23.01, end: 31.87, title: 'Location Offline', subtitle: 'The entire location can fail at once.', takeaway: 'A shared location creates a shared failure boundary.'},
  {id: 'maz-07', kind: 'maz-screen', start: 31.87, end: 38.67, title: 'Multi-AZ Question', subtitle: 'How do systems survive a data-center location failure?', takeaway: 'The next boundary is the Availability Zone.'},
  {id: 'maz-08', kind: 'maz-screen', start: 38.67, end: 45.67, title: 'Welcome Back', subtitle: 'Engineering Systems returns to FoodDash.', takeaway: 'The episode focuses on location-level resilience.'},
  {id: 'maz-09', kind: 'maz-screen', start: 45.67, end: 54.61, title: 'Today', subtitle: 'What is an Availability Zone?', takeaway: 'The lesson starts by naming the cloud boundary.'},
  {id: 'maz-10', kind: 'maz-screen', start: 54.61, end: 62.57, title: 'Why It Matters', subtitle: 'Three servers behind a balancer may still not be enough.', takeaway: 'Multi-AZ helps survive location-level failures.'},
  {id: 'maz-11', kind: 'maz-screen', start: 62.57, end: 69.05, title: 'Cloud Concept', subtitle: 'Before redesigning FoodDash, define the cloud terms.', takeaway: 'The fix needs the right infrastructure model.'},
  {id: 'maz-12', kind: 'maz-screen', start: 69.05, end: 74.73, title: 'Regions', subtitle: 'Cloud providers divide infrastructure geographically.', takeaway: 'A region is a broad geographic area.'},
  {id: 'maz-13', kind: 'maz-screen', start: 74.73, end: 80.71, title: 'Example Regions', subtitle: 'Mumbai, Singapore, and Northern Virginia.', takeaway: 'Regions are separated cloud footprints.'},
  {id: 'maz-14', kind: 'maz-screen', start: 80.71, end: 87.17, title: 'Inside A Region', subtitle: 'Regions contain Availability Zones.', takeaway: 'An AZ is inside a region, not the same thing as a region.'},
  {id: 'maz-15', kind: 'maz-screen', start: 87.17, end: 94.91, title: 'AZ Infrastructure', subtitle: 'Power, networking, and cooling are independent.', takeaway: 'An AZ is designed as an isolated infrastructure location.'},
  {id: 'maz-16', kind: 'maz-screen', start: 94.91, end: 101.63, title: 'Data Centers', subtitle: 'An AZ may contain one or more physical data centers.', takeaway: 'Do not assume one AZ always means one building.'},
  {id: 'maz-17', kind: 'maz-screen', start: 101.63, end: 112.93, title: 'Isolation', subtitle: 'One AZ failure should not bring down another AZ.', takeaway: 'Isolation is the core idea.'},
  {id: 'maz-18', kind: 'maz-screen', start: 112.93, end: 118.63, title: 'Back To FoodDash', subtitle: 'Return to the architecture from previous episodes.', takeaway: 'Now inspect where the known system is placed.'},
  {id: 'maz-19', kind: 'maz-screen', start: 118.63, end: 126.09, title: 'Incoming Requests', subtitle: 'Thousands of requests first arrive at the load balancer.', takeaway: 'The load balancer remains the front door.'},
  {id: 'maz-20', kind: 'maz-screen', start: 126.09, end: 134.45, title: 'Server Pool', subtitle: 'Traffic is distributed to Server A, Server B, and Server C.', takeaway: 'FoodDash has three serving destinations.'},
  {id: 'maz-21', kind: 'maz-screen', start: 134.45, end: 140.7, title: 'Routing Algorithms', subtitle: 'Different algorithms choose between backend servers.', takeaway: 'The balancer can choose where requests go.'},
  {id: 'maz-21b', kind: 'maz-screen', start: 140.7, end: 146.51, title: 'Layer 4 / Layer 7', subtitle: 'Different load balancers route at different network layers.', takeaway: 'Routing intelligence was built in previous episodes.'},
  {id: 'maz-22', kind: 'maz-screen', start: 146.51, end: 157.09, title: 'Previous Episodes', subtitle: 'The current architecture was built step by step.', takeaway: 'This is the FoodDash system viewers already know.'},
  {id: 'maz-23', kind: 'maz-screen', start: 157.09, end: 167.25, title: 'Looks Resilient', subtitle: 'If Server A crashes, traffic goes to B and C.', takeaway: 'The system no longer depends on one app server.'},
  {id: 'maz-24', kind: 'maz-screen', start: 167.25, end: 173.99, title: 'Server B Overloaded', subtitle: 'Traffic can shift toward other available servers.', takeaway: 'Routing protects against overloaded individual machines.'},
  {id: 'maz-25', kind: 'maz-screen', start: 173.99, end: 180.47, title: 'Hidden Problem', subtitle: 'FoodDash no longer depends on one app server, but something is still shared.', takeaway: 'The next risk is physical placement.'},
  {id: 'maz-26', kind: 'maz-screen', start: 180.47, end: 189.01, title: 'All In AZ A', subtitle: 'Server A, B, and C are deployed inside Availability Zone A.', takeaway: 'Three servers can still sit in one AZ.'},
  {id: 'maz-27', kind: 'maz-screen', start: 189.01, end: 198.55, title: 'Three Machines', subtitle: 'Traffic reaches different machines, but the AZ is shared.', takeaway: 'Separate machines are not separate failure boundaries.'},
  {id: 'maz-28', kind: 'maz-screen', start: 198.55, end: 208.23, title: 'Single-AZ', subtitle: 'Server-level redundancy is not location-level redundancy.', takeaway: 'This is a Single-AZ architecture.'},
  {id: 'maz-29', kind: 'maz-screen', start: 208.23, end: 214.67, title: 'AZ Failure', subtitle: 'Availability Zone A has a major infrastructure failure.', takeaway: 'The shared boundary fails first.'},
  {id: 'maz-30', kind: 'maz-screen', start: 214.67, end: 223.97, title: 'No Healthy Backends', subtitle: 'The load balancer can route, but no servers are healthy.', takeaway: 'A working front door is useless without healthy destinations.'},
  {id: 'maz-31', kind: 'maz-screen', start: 223.97, end: 234.35, title: 'Offline', subtitle: 'Three servers and a load balancer still went offline.', takeaway: 'Redundancy failed because the boundary was shared.'},
  {id: 'maz-32', kind: 'maz-screen', start: 234.35, end: 242.0, title: 'Failure Boundary', subtitle: 'Redundancy only helps across independent boundaries.', takeaway: 'Redundant components need independent boundaries.'},
  {id: 'maz-32b', kind: 'maz-screen', start: 242.0, end: 250.51, title: 'AZ Boundary Limit', subtitle: 'One AZ failure still defeats every server inside it.', takeaway: 'A whole AZ failure defeats servers inside that AZ.'},
  {id: 'maz-33', kind: 'maz-screen', start: 250.51, end: 257.8, title: 'Redesign Begins', subtitle: 'FoodDash keeps the Mumbai region.', takeaway: 'The same region can contain multiple failure boundaries.'},
  {id: 'maz-33b', kind: 'maz-screen', start: 257.8, end: 263.67, title: 'Split The Zones', subtitle: 'Servers move out of one shared zone.', takeaway: 'The app tier will span multiple AZs.'},
  {id: 'maz-34', kind: 'maz-screen', start: 263.67, end: 267.33, title: 'Server A', subtitle: 'Server A moves to Availability Zone A.', takeaway: 'Each server receives a zone placement.'},
  {id: 'maz-35', kind: 'maz-screen', start: 267.33, end: 276.15, title: 'Server B And C', subtitle: 'Server B moves to AZ B and Server C moves to AZ C.', takeaway: 'The app tier now spans zones.'},
  {id: 'maz-36', kind: 'maz-screen', start: 276.15, end: 284.51, title: 'Multi-AZ', subtitle: 'The load balancer routes across zone-separated servers.', takeaway: 'Same region, different failure boundaries.'},
  {id: 'maz-37', kind: 'maz-screen', start: 284.51, end: 292.53, title: 'Normal Operation', subtitle: 'All three AZs can serve traffic.', takeaway: 'Every zone participates while healthy.'},
  {id: 'maz-38', kind: 'maz-screen', start: 292.53, end: 300.45, title: 'Request Rotation', subtitle: 'Requests go to AZ A, AZ B, and AZ C.', takeaway: 'Traffic crosses multiple failure boundaries.'},
  {id: 'maz-39', kind: 'maz-screen', start: 300.45, end: 309.55, title: 'AZ A Offline', subtitle: 'Zone A fails and Server A becomes unavailable.', takeaway: 'One zone can still fail.'},
  {id: 'maz-40', kind: 'maz-screen', start: 309.55, end: 315.01, title: 'Remove From Rotation', subtitle: 'The load balancer detects Server A is unhealthy.', takeaway: 'Health checks keep broken targets out of rotation.'},
  {id: 'maz-41', kind: 'maz-screen', start: 315.01, end: 321.97, title: 'Route To B And C', subtitle: 'Traffic continues through Zone B and Zone C.', takeaway: 'The service still has healthy destinations.'},
  {id: 'maz-42', kind: 'maz-screen', start: 321.97, end: 329.01, title: 'Less Capacity', subtitle: 'FoodDash temporarily has less total capacity.', takeaway: 'Multi-AZ failure is degraded service, not magic.'},
  {id: 'maz-43', kind: 'maz-screen', start: 329.01, end: 333.25, title: 'Higher Traffic', subtitle: 'The remaining servers handle more load.', takeaway: 'Surviving zones carry extra pressure.'},
  {id: 'maz-44', kind: 'maz-screen', start: 333.25, end: 341.49, title: 'Partial Failure', subtitle: 'The service keeps operating through a designed failure.', takeaway: 'Multi-AZ turns outage into partial capacity loss.'},
  {id: 'maz-45', kind: 'maz-screen', start: 341.49, end: 351.95, title: 'Only One Part', subtitle: 'App servers are distributed, but the database can still be single-AZ.', takeaway: 'Compute resilience is not complete service resilience.'},
  {id: 'maz-46', kind: 'maz-screen', start: 351.95, end: 358.81, title: 'Zone A Fails Again', subtitle: 'Servers B and C keep running.', takeaway: 'Healthy compute can remain alive.'},
  {id: 'maz-47', kind: 'maz-screen', start: 358.81, end: 365.51, title: 'Database Missing', subtitle: 'Servers B and C cannot access the database.', takeaway: 'A broken dependency breaks the request path.'},
  {id: 'maz-48', kind: 'maz-screen', start: 365.51, end: 371.71, title: 'Critical Dependencies', subtitle: 'Caches, brokers, storage, and other dependencies matter too.', takeaway: 'Every required dependency has a failure boundary.'},
  {id: 'maz-49', kind: 'maz-screen', start: 371.71, end: 376.97, title: 'Complete Path', subtitle: 'A resilient architecture considers the full request path.', takeaway: 'Availability is judged end to end.'},
  {id: 'maz-50', kind: 'maz-screen', start: 376.97, end: 386.77, title: 'Replicate And Fail Over', subtitle: 'App servers, data, and dependencies must all survive AZ loss.', takeaway: 'The design must include data replication and dependency failover.'},
  {id: 'maz-51', kind: 'maz-screen', start: 386.77, end: 393.11, title: 'Real Readiness', subtitle: 'Health checks must route only to resources that can serve requests.', takeaway: 'Healthy means the whole path can work.'},
  {id: 'maz-52', kind: 'maz-screen', start: 393.11, end: 403.73, title: 'Not Just Boxes', subtitle: 'Multi-AZ is not simply spreading machines across a diagram.', takeaway: 'The service must survive losing one AZ.'},
  {id: 'maz-53', kind: 'maz-screen', start: 403.73, end: 412.23, title: 'Summary: Servers', subtitle: 'Multiple servers in one AZ protect against individual server failures.', takeaway: 'Server redundancy handles machine-level failure.'},
  {id: 'maz-54', kind: 'maz-screen', start: 412.23, end: 419.67, title: 'Summary: AZs', subtitle: 'Multiple AZs in one region protect against a location failure.', takeaway: 'Location redundancy handles AZ-level failure.'},
  {id: 'maz-55', kind: 'maz-screen', start: 419.67, end: 427.17, title: 'Still One Region', subtitle: 'FoodDash is still only in Mumbai.', takeaway: 'The next boundary is the region.'},
  {id: 'maz-56', kind: 'maz-screen', start: 427.17, end: 439.15, title: 'Region Failure?', subtitle: 'Could Singapore or Northern Virginia serve traffic?', takeaway: 'Multi-region design is the next resilience step.'},
  {id: 'maz-57', kind: 'maz-screen', start: 439.15, end: 450.99, title: 'Next Episode', subtitle: 'How do users route across regions thousands of kilometers apart?', takeaway: 'FoodDash is heading toward Multi-Region Architecture.'},
  {id: 'maz-58', kind: 'closing', start: 450.99, end: 460.0, title: 'Engineering Systems', subtitle: 'Subscribe', takeaway: 'The series builds FoodDash step by step.'},
];
