import type {LessonBeat} from '../../types';

export const lessonPlan: LessonBeat[] = [
  {
    id: 'spof-video-intro',
    kind: 'spof-video-intro',
    start: 0,
    end: 5.27,
    title: 'Engineering Systems',
    subtitle: 'Availability Patterns #2: Single Point of Failures',
    takeaway: 'We continue the availability path with the first failure pattern to spot.',
  },
  {
    id: 'spof-recap',
    kind: 'spof-recap',
    start: 5.27,
    end: 23.47,
    title: 'Quick Recap',
    subtitle: 'Availability is uptime translated into business reality.',
    takeaway: 'Percentages become minutes of downtime and visible business risk.',
  },
  {
    id: 'spof-start-availability',
    kind: 'spof-start-availability',
    start: 23.47,
    end: 27.31,
    title: 'Let\'s Get Started',
    subtitle: 'Into availability, one failure path at a time.',
    takeaway: 'The next piece is where a single component can pull everything down.',
  },
  {
    id: 'spof-agenda',
    kind: 'spof-agenda',
    start: 27.31,
    end: 43.23,
    title: 'Agenda Timeline',
    subtitle: 'Six stops through the anatomy of single points of failure.',
    takeaway: 'Today moves from the equation to practical high availability steps.',
  },
  {
    id: 'spof-section-availability-equation',
    kind: 'spof-section-heading',
    start: 43.23,
    end: 48.59,
    title: 'Availability Equation',
    subtitle: 'uptime to reality',
    takeaway: 'The math matters because outages become real-world consequences.',
  },
  {
    id: 'spof-availability-question',
    kind: 'spof-availability-question',
    start: 48.59,
    end: 85.85,
    title: 'Why Do Systems Go Down?',
    subtitle: 'Uptime, business health, and outages in the news.',
    takeaway: 'Availability failures are practical engineering failures, not abstract math.',
  },
  {
    id: 'spof-section-defining',
    kind: 'spof-section-heading',
    start: 85.85,
    end: 91.47,
    title: 'Defining SPOFs',
    subtitle: 'the critical component',
    takeaway: 'A single dependency can become the component everything relies on.',
  },
  {
    id: 'spof-network-definition',
    kind: 'spof-network-definition',
    start: 91.47,
    end: 120.07,
    title: 'Single Point Of Failure',
    subtitle: 'Any component whose failure causes the entire system to become unavailable.',
    takeaway: 'Web servers, load balancers, switches, regions, and services can all become SPOFs.',
  },
  {
    id: 'spof-green-red',
    kind: 'spof-green-red',
    start: 120.07,
    end: 124.75,
    title: 'If This Thing Dies',
    subtitle: 'everything dies',
    takeaway: 'A healthy-looking system can turn unavailable from one failed center.',
  },
  {
    id: 'spof-home-appliances',
    kind: 'spof-home-appliances',
    start: 124.75,
    end: 148.31,
    title: 'Home Network Example',
    subtitle: 'One breaker, every appliance downstream.',
    takeaway: 'The main breaker is the simple mental model for a single point of failure.',
  },
  {
    id: 'spof-section-fooddash',
    kind: 'spof-section-heading',
    start: 148.31,
    end: 153.93,
    title: 'FoodDash Outage',
    subtitle: 'Evening Dinner Rush',
    takeaway: 'Now we ground the idea in a realistic food delivery incident.',
  },
  {
    id: 'spof-order-process',
    kind: 'spof-order-process',
    start: 153.93,
    end: 180,
    title: 'Order Process',
    subtitle: 'Customers, restaurants, and partners move in sequence.',
    takeaway: 'Every successful order depends on multiple actors staying connected.',
  },
  {
    id: 'spof-broken-database',
    kind: 'spof-broken-database',
    start: 180,
    end: 220.97,
    title: 'FoodDash Goes Down',
    subtitle: 'Mobile app and servers still run, but the database breaks.',
    takeaway: 'One crashed database can paralyze an otherwise healthy-looking platform.',
  },
  {
    id: 'spof-section-hidden-chains',
    kind: 'spof-section-heading',
    start: 220.97,
    end: 226.49,
    title: 'Hidden Chains',
    subtitle: 'Illusion of redundancy',
    takeaway: 'Redundancy in one layer can hide a SPOF in another layer.',
  },
  {
    id: 'spof-hidden-comparison',
    kind: 'spof-hidden-comparison',
    start: 226.49,
    end: 278.69,
    title: 'Hidden Dependency Chains',
    subtitle: 'Two servers can still share one fatal dependency.',
    takeaway: 'The database remains a catastrophic SPOF even after app-layer redundancy.',
  },
  {
    id: 'spof-failure-chain',
    kind: 'spof-failure-chain',
    start: 278.69,
    end: 313.99,
    title: 'Dependency Chain',
    subtitle: 'Every link can stop a different part of the business.',
    takeaway: 'Availability depends on each critical link functioning correctly.',
  },
  {
    id: 'spof-disappear-question',
    kind: 'spof-disappear-question',
    start: 313.99,
    end: 326.77,
    title: 'Hidden Trap Heuristic',
    subtitle: 'What if this component suddenly disappears?',
    takeaway: 'This question reveals hidden single points of failure.',
  },
  {
    id: 'spof-fooddash-scan',
    kind: 'spof-fooddash-scan',
    start: 326.77,
    end: 343.83,
    title: 'FoodDash Architecture Scan',
    subtitle: 'Server, switch, region: what if each one dies?',
    takeaway: 'If one missing component stops all users, you found a hidden SPOF.',
  },
  {
    id: 'spof-section-operational',
    kind: 'spof-section-heading',
    start: 343.83,
    end: 347.53,
    title: 'Operational Failures',
    subtitle: 'Human Bottlenecks',
    takeaway: 'Not every SPOF is technical.',
  },
  {
    id: 'spof-central-quote',
    kind: 'spof-central-quote',
    start: 347.53,
    end: 376.21,
    title: 'Operational SPOFs',
    subtitle: 'Infrastructure is only part of the risk.',
    takeaway: 'Good engineering removes dependency on any single component, process, or person.',
  },
  {
    id: 'spof-human-cloud',
    kind: 'spof-human-cloud',
    start: 376.21,
    end: 403.09,
    title: 'Human Bottleneck',
    subtitle: 'A redundant cloud can still rely on one person.',
    takeaway: 'A single unavailable person can become a massive operational SPOF.',
  },
  {
    id: 'spof-section-high-availability',
    kind: 'spof-section-heading',
    start: 403.09,
    end: 408.77,
    title: 'High Availability Steps',
    subtitle: 'Identifying SPOFs',
    takeaway: 'Finding SPOFs is step one.',
  },
  {
    id: 'spof-tech-human',
    kind: 'spof-tech-human',
    start: 408.77,
    end: 416.95,
    title: 'Find Technical And Human SPOFs',
    subtitle: 'Server, database, engineer.',
    takeaway: 'Actively finding both technical and human SPOFs is crucial.',
  },
  {
    id: 'spof-first-step',
    kind: 'spof-first-step',
    start: 416.95,
    end: 419.31,
    title: 'First Step',
    subtitle: 'Foundational and non-negotiable.',
    takeaway: 'Find SPOFs before designing around them.',
  },
  {
    id: 'spof-blank-canvas',
    kind: 'spof-blank-canvas',
    start: 419.31,
    end: 421.17,
    title: 'Before You Design',
    subtitle: 'Start with the blank architecture canvas.',
    takeaway: 'Design begins after the risks are visible.',
  },
  {
    id: 'spof-fault-tolerant-canvas',
    kind: 'spof-fault-tolerant-canvas',
    start: 421.17,
    end: 423.05,
    title: 'Fault Tolerant Architecture',
    subtitle: 'Load balancer, two apps, replicated database.',
    takeaway: 'Fault tolerance is deliberate structure, not decoration.',
  },
  {
    id: 'spof-vulnerability-zoom',
    kind: 'spof-vulnerability-zoom',
    start: 423.05,
    end: 426.11,
    title: 'Know The Vulnerabilities',
    subtitle: 'Database, engineer, single server.',
    takeaway: 'You must know exactly where the vulnerabilities are.',
  },
  {
    id: 'spof-own-walls',
    kind: 'spof-own-walls',
    start: 426.11,
    end: 430.27,
    title: 'Within Your Own Walls',
    subtitle: 'Internal architecture, internal process, internal risk.',
    takeaway: 'Look for risks inside your own system boundaries.',
  },
  {
    id: 'spof-failure-paths',
    kind: 'spof-failure-paths',
    start: 430.27,
    end: 434.65,
    title: 'Every SPOF',
    subtitle: 'Another failure path.',
    takeaway: 'Every SPOF creates another way for the system to become unavailable.',
  },
  {
    id: 'spof-fragility-meter',
    kind: 'spof-fragility-meter',
    start: 434.65,
    end: 439.21,
    title: 'Fragility Meter',
    subtitle: 'More dependencies, more fragility.',
    takeaway: 'Unmitigated dependencies make the platform fragile.',
  },
  {
    id: 'spof-minimize-dependencies',
    kind: 'spof-minimize-dependencies',
    start: 439.21,
    end: 443.61,
    title: 'Minimize Dependencies',
    subtitle: 'Design from the ground up.',
    takeaway: 'Modern systems minimize critical dependencies.',
  },
  {
    id: 'spof-scan-cards',
    kind: 'spof-scan-cards',
    start: 443.61,
    end: 451.41,
    title: 'Scan The Whole System',
    subtitle: 'Infrastructure, software, vendors, processes.',
    takeaway: 'Comb through every layer to root out SPOFs.',
  },
  {
    id: 'spof-complete-checklist',
    kind: 'spof-complete-checklist',
    start: 451.41,
    end: 453.71,
    title: 'Path Forward',
    subtitle: 'Find, assess, remove.',
    takeaway: 'The path forward starts with a completed SPOF checklist.',
  },
  {
    id: 'spof-learned-title',
    kind: 'spof-learned-title',
    start: 453.71,
    end: 454.81,
    title: 'What Did We Learn?',
    subtitle: 'A quick recap before the next pattern.',
    takeaway: 'Now we compress the lesson.',
  },
  {
    id: 'spof-summary-takedown',
    kind: 'spof-summary-takedown',
    start: 454.81,
    end: 459.07,
    title: 'Summary One',
    subtitle: 'A SPOF can take down everything.',
    takeaway: 'A single point of failure can bring down the entire system.',
  },
  {
    id: 'spof-summary-everywhere',
    kind: 'spof-summary-everywhere',
    start: 459.07,
    end: 466.85,
    title: 'Summary Two',
    subtitle: 'SPOFs hide everywhere.',
    takeaway: 'SPOFs can exist in infrastructure, software, vendors, people, and processes.',
  },
  {
    id: 'spof-summary-minimize',
    kind: 'spof-summary-minimize',
    start: 466.85,
    end: 471.03,
    title: 'Summary Three',
    subtitle: 'Minimize critical dependencies.',
    takeaway: 'Modern systems should minimize critical dependencies.',
  },
  {
    id: 'spof-summary-foundation',
    kind: 'spof-summary-foundation',
    start: 471.03,
    end: 475.29,
    title: 'Summary Four',
    subtitle: 'Identify SPOFs supports high availability.',
    takeaway: 'Identifying SPOFs is step one toward high availability.',
  },
  {
    id: 'spof-timeline-complete',
    kind: 'spof-timeline-complete',
    start: 475.29,
    end: 478.29,
    title: 'Availability Path',
    subtitle: 'Availability to SPOF to redundancy.',
    takeaway: 'SPOF builds directly on the previous availability lesson.',
  },
  {
    id: 'spof-next-redundancy',
    kind: 'spof-next-redundancy',
    start: 478.29,
    end: 482.73,
    title: 'Next Episode',
    subtitle: 'Redundancy',
    takeaway: 'Redundancy is the next step toward high availability.',
  },
  {
    id: 'spof-redundancy-preview',
    kind: 'spof-redundancy-preview',
    start: 482.73,
    end: 487.85,
    title: 'Failure Prevention',
    subtitle: 'Single server becomes multiple servers.',
    takeaway: 'Engineers eliminate risks by removing single-server dependency.',
  },
  {
    id: 'spof-subscribe',
    kind: 'spof-subscribe',
    start: 487.85,
    end: 493.95,
    title: 'Engineering Systems',
    subtitle: 'Subscribe for the availability patterns series.',
    takeaway: 'Follow the series to keep building the reliability toolkit.',
  },
  {
    id: 'spof-final-question',
    kind: 'spof-final-question',
    start: 493.95,
    end: 500.63,
    title: 'Final Question',
    subtitle: 'What hidden component does your architecture rely on?',
    takeaway: 'Find the hidden component before it becomes the outage.',
  },
  {
    id: 'spof-common-outro',
    kind: 'closing',
    start: 500.63,
    end: 501.41,
    title: 'Engineering Systems',
    subtitle: 'See you in the next one.',
    takeaway: 'Thanks for watching.',
  },
];
