import type {LessonBeat} from '../../types';

export const lessonPlan: LessonBeat[] = [
  {
    id: 'hc-01',
    kind: 'hc-screen',
    start: 0,
    end: 8,
    title: 'Health Checks & Failover',
    subtitle: 'FoodDash returns to availability patterns.',
    takeaway: 'Detection and recovery turn redundancy into availability.',
  },
  {
    id: 'hc-02',
    kind: 'hc-screen',
    start: 8,
    end: 13.714,
    title: 'Recap: SPOF Removed',
    subtitle: 'Redundancy and replication eliminated the single database risk.',
    takeaway: 'We removed one failure point, but the system still needs awareness.',
  },
  {
    id: 'hc-03',
    kind: 'hc-screen',
    start: 13.714,
    end: 23.143,
    title: 'Two Databases',
    subtitle: 'Primary handles live traffic. Secondary receives replicated data.',
    takeaway: 'A synchronized backup is ready, but readiness is not recovery.',
  },
  {
    id: 'hc-04',
    kind: 'hc-screen',
    start: 23.143,
    end: 31,
    title: 'Solved?',
    subtitle: 'The architecture looks complete, but one gap is still hidden.',
    takeaway: 'The missing piece is failure detection.',
  },
  {
    id: 'hc-05',
    kind: 'hc-screen',
    start: 31,
    end: 41,
    title: 'Primary Crashes',
    subtitle: 'The backup is fully replicated and ready to jump in.',
    takeaway: 'A backup can be ready while the system still has no trigger.',
  },
  {
    id: 'hc-06',
    kind: 'hc-screen',
    start: 41,
    end: 49.438,
    title: 'Who Notices?',
    subtitle: 'How does the system know the primary failed?',
    takeaway: 'Failover cannot begin until the system has evidence.',
  },
  {
    id: 'hc-06b',
    kind: 'hc-screen',
    start: 49.438,
    end: 53.316,
    title: 'Backup Still Useless',
    subtitle: 'Nobody knows when to switch over to it.',
    takeaway: 'The backup needs an automatic trigger.',
  },
  {
    id: 'hc-07',
    kind: 'hc-screen',
    start: 53.316,
    end: 61,
    title: 'Health Checks',
    subtitle: 'A simple automated digital pulse.',
    takeaway: 'The system keeps asking: are you still alive?',
  },
  {
    id: 'hc-08',
    kind: 'hc-screen',
    start: 61,
    end: 70,
    title: 'Tiny Request',
    subtitle: 'FoodDash sends a background check to the primary database.',
    takeaway: 'Health checks are small requests with big operational meaning.',
  },
  {
    id: 'hc-09',
    kind: 'hc-screen',
    start: 70,
    end: 78.5,
    title: 'Ping. Response.',
    subtitle: 'The database answers, then answers again.',
    takeaway: 'Healthy systems keep returning expected signals.',
  },
  {
    id: 'hc-10',
    kind: 'hc-screen',
    start: 78.5,
    end: 84.75,
    title: 'Invisible Loop',
    subtitle: 'Customers ordering lunch never know checks are happening.',
    takeaway: 'Monitoring should run quietly behind the product experience.',
  },
  {
    id: 'hc-11',
    kind: 'hc-screen',
    start: 84.75,
    end: 91.6,
    title: 'Break Something',
    subtitle: 'The primary database suddenly crashes.',
    takeaway: 'The next check is where detection starts.',
  },
  {
    id: 'hc-12',
    kind: 'hc-screen',
    start: 91.6,
    end: 97.2,
    title: 'Repeated Silence',
    subtitle: 'One check fails. Another fails. Then another.',
    takeaway: 'Silence matters when a response was expected.',
  },
  {
    id: 'hc-13',
    kind: 'hc-screen',
    start: 97.2,
    end: 105.176,
    title: 'Hard Evidence',
    subtitle: 'FoodDash can conclude the primary is undeniably down.',
    takeaway: 'Health checks convert missing responses into certainty.',
  },
  {
    id: 'hc-14',
    kind: 'hc-screen',
    start: 105.176,
    end: 114,
    title: 'Failover',
    subtitle: 'Move traffic away from broken and toward healthy.',
    takeaway: 'Failover is the automated response to detected failure.',
  },
  {
    id: 'hc-15',
    kind: 'hc-screen',
    start: 114,
    end: 119.357,
    title: 'Sequence Begins',
    subtitle: 'An exact automated recovery sequence starts.',
    takeaway: 'Failover is a chain of small coordinated actions.',
  },
  {
    id: 'hc-16',
    kind: 'hc-screen',
    start: 119.357,
    end: 124.4,
    title: 'Detect',
    subtitle: 'The system confirms the failure.',
    takeaway: 'Step one is confidence that the old primary is dead.',
  },
  {
    id: 'hc-17',
    kind: 'hc-screen',
    start: 124.4,
    end: 128.4,
    title: 'Promote',
    subtitle: 'The synchronized backup becomes the new primary.',
    takeaway: 'The standby copy becomes the active system of record.',
  },
  {
    id: 'hc-18',
    kind: 'hc-screen',
    start: 128.4,
    end: 130.714,
    title: 'Redirect',
    subtitle: 'Live traffic moves to the promoted database.',
    takeaway: 'Traffic must follow the healthy component.',
  },
  {
    id: 'hc-19',
    kind: 'hc-screen',
    start: 130.714,
    end: 135,
    title: 'Reconnect',
    subtitle: 'Application servers reconnect and FoodDash keeps running.',
    takeaway: 'Recovery completes when application traffic resumes.',
  },
  {
    id: 'hc-20',
    kind: 'hc-screen',
    start: 135,
    end: 137.842,
    title: 'What Did Not Happen',
    subtitle: 'The important part is the manual work that never happened.',
    takeaway: 'Automatic recovery removes the human waiting step.',
  },
  {
    id: 'hc-21',
    kind: 'hc-screen',
    start: 137.842,
    end: 148.059,
    title: 'No Human Needed',
    subtitle: 'Nobody woke up, logged in, or typed emergency config.',
    takeaway: 'The system should not depend on a 3 AM manual rescue.',
  },
  {
    id: 'hc-22',
    kind: 'hc-screen',
    start: 148.059,
    end: 155.333,
    title: 'Self-Healing',
    subtitle: 'The system spotted the problem and fixed itself.',
    takeaway: 'That is the real power of automatic failover.',
  },
  {
    id: 'hc-23',
    kind: 'hc-screen',
    start: 155.333,
    end: 166.75,
    title: 'Real Systems Are Messy',
    subtitle: 'Heavy queries, lost packets, and temporary spikes happen.',
    takeaway: 'Not every failed check means a component is truly dead.',
  },
  {
    id: 'hc-24',
    kind: 'hc-screen',
    start: 166.75,
    end: 176.333,
    title: 'False Alarm Risk',
    subtitle: 'One missed check could trigger a massive failover.',
    takeaway: 'Reacting instantly to one miss makes platforms unstable.',
  },
  {
    id: 'hc-25',
    kind: 'hc-screen',
    start: 176.333,
    end: 182.8,
    title: 'False Positives',
    subtitle: 'The system gets jumpy and assumes something died.',
    takeaway: 'A false positive is a failure of judgment, not hardware.',
  },
  {
    id: 'hc-26',
    kind: 'hc-screen',
    start: 182.8,
    end: 190.571,
    title: 'Never Trust One',
    subtitle: 'A single failed check is not enough in production.',
    takeaway: 'Production systems need evidence, not panic.',
  },
  {
    id: 'hc-27',
    kind: 'hc-screen',
    start: 190.571,
    end: 195.2,
    title: 'Thresholds',
    subtitle: 'Require multiple failed checks over time.',
    takeaway: 'Thresholds separate signal from noise.',
  },
  {
    id: 'hc-28',
    kind: 'hc-screen',
    start: 195.2,
    end: 203.375,
    title: 'Three Strikes',
    subtitle: 't0, t+5 seconds, t+10 seconds.',
    takeaway: 'Repeated failures tell a clearer story than one miss.',
  },
  {
    id: 'hc-29',
    kind: 'hc-screen',
    start: 203.375,
    end: 209.2,
    title: 'Declare Dead',
    subtitle: 'Only after three consecutive failed checks.',
    takeaway: 'The declaration comes after a confirmed pattern.',
  },
  {
    id: 'hc-30',
    kind: 'hc-screen',
    start: 209.2,
    end: 216.875,
    title: 'Perfect Balance',
    subtitle: 'Catch genuine failures fast. Avoid chaotic failovers.',
    takeaway: 'Good thresholds keep recovery fast without becoming jumpy.',
  },
  {
    id: 'hc-31',
    kind: 'hc-screen',
    start: 216.875,
    end: 223,
    title: 'Pattern Everywhere',
    subtitle: 'The same idea is not just for databases.',
    takeaway: 'Health checks are a universal availability primitive.',
  },
  {
    id: 'hc-32',
    kind: 'hc-screen',
    start: 223,
    end: 233,
    title: 'Up The Stack',
    subtitle: 'Shift from databases to app servers and load balancers.',
    takeaway: 'The same detection pattern applies at every layer.',
  },
  {
    id: 'hc-33',
    kind: 'hc-screen',
    start: 233,
    end: 239.8,
    title: 'Server Cluster',
    subtitle: 'Four backend servers sit behind a load balancer.',
    takeaway: 'Load balancers need health signals for every backend.',
  },
  {
    id: 'hc-34',
    kind: 'hc-screen',
    start: 239.8,
    end: 245.8,
    title: 'Continuous Checks',
    subtitle: 'The load balancer checks each machine.',
    takeaway: 'Every backend stays in rotation only while it looks healthy.',
  },
  {
    id: 'hc-35',
    kind: 'hc-screen',
    start: 245.8,
    end: 254.5,
    title: 'All Healthy',
    subtitle: 'All four servers are routing food orders.',
    takeaway: 'A healthy cluster has multiple active serving paths.',
  },
  {
    id: 'hc-36',
    kind: 'hc-screen',
    start: 254.5,
    end: 257.8,
    title: 'Server Three Crashes',
    subtitle: 'One backend drops out of the cluster.',
    takeaway: 'The cluster should degrade, not collapse.',
  },
  {
    id: 'hc-37',
    kind: 'hc-screen',
    start: 257.8,
    end: 267.333,
    title: 'Removed From Rotation',
    subtitle: 'The load balancer spots failing checks and removes server three.',
    takeaway: 'Isolation happens automatically once health checks fail.',
  },
  {
    id: 'hc-38',
    kind: 'hc-screen',
    start: 267.333,
    end: 273.786,
    title: 'Traffic Reroutes',
    subtitle: 'New orders go to the remaining healthy servers.',
    takeaway: 'Customers keep moving through healthy paths.',
  },
  {
    id: 'hc-39',
    kind: 'hc-screen',
    start: 273.786,
    end: 282.333,
    title: 'Customers Never Notice',
    subtitle: 'A server died in the background, but ordering continues.',
    takeaway: 'Good failover protects the customer experience.',
  },
  {
    id: 'hc-40',
    kind: 'hc-screen',
    start: 282.333,
    end: 289.143,
    title: 'Server Reboots',
    subtitle: 'Server three comes back online.',
    takeaway: 'Recovery also needs a path back into service.',
  },
  {
    id: 'hc-41',
    kind: 'hc-screen',
    start: 289.143,
    end: 301,
    title: 'Rejoin Rotation',
    subtitle: 'Successful checks mark the server healthy again.',
    takeaway: 'The system pulls out the bad and tags the good back in.',
  },
  {
    id: 'hc-42',
    kind: 'hc-screen',
    start: 301,
    end: 307.769,
    title: 'Engineering Mantra',
    subtitle: 'Never assume failover works. Test it.',
    takeaway: 'Untested recovery is only a theory.',
  },
  {
    id: 'hc-43',
    kind: 'hc-screen',
    start: 307.769,
    end: 312.818,
    title: 'Controlled Shutdowns',
    subtitle: 'Intentionally shut down servers in safe environments.',
    takeaway: 'Practice failure before production gives you no choice.',
  },
  {
    id: 'hc-44',
    kind: 'hc-screen',
    start: 312.818,
    end: 319.8,
    title: 'Simulate Outages',
    subtitle: 'Validate recovery mechanisms before a real incident.',
    takeaway: 'Simulations prove whether the automation actually works.',
  },
  {
    id: 'hc-45',
    kind: 'hc-screen',
    start: 319.8,
    end: 327.563,
    title: 'Worst Time To Learn',
    subtitle: 'Do not discover broken failover during a 2 AM outage.',
    takeaway: 'Test recovery before the incident tests you.',
  },
  {
    id: 'hc-46',
    kind: 'hc-screen',
    start: 327.563,
    end: 334.273,
    title: 'FoodDash System',
    subtitle: 'A quick summary of the resilience stack.',
    takeaway: 'Each layer contributes a different survival mechanism.',
  },
  {
    id: 'hc-47',
    kind: 'hc-screen',
    start: 334.273,
    end: 337.455,
    title: 'Redundancy + Replication',
    subtitle: 'Backup infrastructure and synchronized copies.',
    takeaway: 'Redundancy gives capacity; replication keeps state ready.',
  },
  {
    id: 'hc-48',
    kind: 'hc-screen',
    start: 337.455,
    end: 344.083,
    title: 'Health Checks + Failover',
    subtitle: 'Eyes on failures and traffic redirection.',
    takeaway: 'Detection and movement make recovery automatic.',
  },
  {
    id: 'hc-49',
    kind: 'hc-screen',
    start: 344.083,
    end: 352.923,
    title: 'Load Balancers + Testing',
    subtitle: 'App-side recovery and proof that it works.',
    takeaway: 'Automation needs continuous validation.',
  },
  {
    id: 'hc-50',
    kind: 'hc-screen',
    start: 352.923,
    end: 358.933,
    title: 'Working Together',
    subtitle: 'Massive failures with basically zero downtime.',
    takeaway: 'Availability comes from coordinated layers, not one feature.',
  },
  {
    id: 'hc-51',
    kind: 'hc-screen',
    start: 358.933,
    end: 366.765,
    title: 'One Question Remains',
    subtitle: 'We can recover quickly, but what target is enough?',
    takeaway: 'Recovery speed matters only relative to an availability target.',
  },
  {
    id: 'hc-52',
    kind: 'hc-screen',
    start: 366.765,
    end: 373.846,
    title: 'Acceptable Downtime',
    subtitle: 'How much downtime can FoodDash tolerate?',
    takeaway: 'Availability turns downtime into a business decision.',
  },
  {
    id: 'hc-53',
    kind: 'hc-screen',
    start: 373.846,
    end: 380,
    title: 'Measure Availability',
    subtitle: 'Teams define how much downtime the business can handle.',
    takeaway: 'Reliability targets formalize acceptable failure.',
  },
  {
    id: 'hc-54',
    kind: 'hc-screen',
    start: 380,
    end: 390.4,
    title: '99.9%',
    subtitle: 'Every extra nine gets exponentially harder.',
    takeaway: 'The famous nines drive architecture complexity.',
  },
  {
    id: 'hc-55',
    kind: 'hc-screen',
    start: 390.4,
    end: 396.25,
    title: 'Next: Availability Targets',
    subtitle: 'The famous nines and what they really mean.',
    takeaway: 'SLA math defines how reliable the system must be.',
  },
  {
    id: 'hc-56',
    kind: 'closing',
    start: 396.25,
    end: 403,
    title: 'Engineering Systems',
    subtitle: 'See you in the next explainer.',
    takeaway: 'Thanks for watching.',
  },
];
