import type {LessonBeat, WordTiming} from '../../types';

const segments: Array<[number, number, string]> = [
  [0, 5, "Welcome back to Engineering Systems. Today, we're continuing our Availability Patterns"],
  [5, 10, 'Explainer, jumping right back into our real-world example of FoodDash to explore'],
  [10, 15, 'how systems automatically bounce back from failure. Now, last time, we upgraded FoodDash'],
  [15, 20, 'by adding redundancy and replication, right? We proved how absolutely crucial having backup'],
  [20, 26, 'infrastructure is. But, as we are about to see, having a backup is really only half the battle,'],
  [26, 29, "because redundancy alone just isn't quite enough."],
  [29, 34, 'Think about it like this. We have a perfectly replicated backup database ready to go.'],
  [34, 39, 'But how does the system actually know to use it? Sure, redundancy gives us that safety net.'],
  [39, 43, 'But without an automated way to detect a failure and actually redirect the traffic,'],
  [43, 49, 'our hungry FoodDash users are just stuck. They are waiting for a human engineer to notice the alert,'],
  [49, 55, 'grab their laptop, log in, and manually fix things. And let us be real, in modern distributed systems,'],
  [55, 60, 'humans are simply way too slow. So, that brings us to our first section,'],
  [60, 64, 'Health Checks and Detecting Failures. Let us dive into how we actually spot these issues'],
  [64, 70, 'the second they happen. At its core, a health check is a small, continuous test used to verify'],
  [70, 76, 'if a system component can still actually serve traffic. But here is what is really interesting.'],
  [76, 80, 'A good health check goes way beyond just pinging a server to see if it is awake.'],
  [80, 86, 'Why? Well, imagine an API returning a 200 OK status. It is happily telling you its web server'],
  [86, 91, 'is running. But behind the scenes, it is completely failing to talk to a critical database or a cache'],
  [91, 97, 'like Redis. So yeah, it is technically alive, but it is practically useless to the person trying'],
  [97, 102, 'to order a pizza. To solve this problem, engineers structure health checks in layers.'],
  [102, 106, 'It is kind of like a pyramid. At the very bottom, we check process health. Basically,'],
  [106, 110, 'is the process running and is the port open? Move up a level, and we have application health.'],
  [110, 114, 'Can the app load its configs and reach its downstream dependencies? And then,'],
  [114, 119, 'right at the top, the ultimate test, business health. Can FoodDash actually place an order?'],
  [119, 124, 'Can it calculate the delivery fee? The huge takeaway here is that true availability means'],
  [124, 132, 'the system can successfully serve the user. It is not just about keeping a machine powered on in some data center somewhere.'],
  [132, 137, 'OK, so what actually happens when one of those health checks repeatedly fails? Well, that brings us to our next section,'],
  [137, 142, 'failover and automatic traffic redirection. Let us see how this builds into an actual recovery plan.'],
  [142, 147, 'Remember our active passive FoodDash database setup? Automatic failover there follows three really distinct steps.'],
  [147, 152, 'Step one, the system detects multiple failed health checks and realizes that the primary database is dead'],
  [152, 156, 'and it is no longer safe to use. Step two, it promotes the secondary replicated backup to be the new primary.'],
  [156, 161, 'And step three, it actively redirects all that application traffic over to the new primary.'],
  [161, 166, 'By automating this whole shebang, we take what could be a massive, hours-long nightmare of an outage'],
  [166, 171, 'and shrink it down to just a tiny brief slowdown or maybe a few dropped requests for the user.'],
  [171, 175, 'But hey, we all know distributed systems are messy, right? Failover is never quite that simple in practice.'],
  [175, 181, 'Let us look at the big engineering challenge here, false positives. Here is the failing over immediately'],
  [181, 187, 'after just one single missed health check is a recipe for disaster. It represents a fundamental trade-off'],
  [187, 193, 'we face in availability engineering. Look at the low threshold approach. It gives you incredibly fast detection,'],
  [193, 197, 'which sounds great for recovery time, but it brings a dangerously high risk of false alarms'],
  [197, 201, 'and system instability. I mean, literally just a tiny network blip or a garbage collection pause'],
  [201, 206, 'could trigger a massive, completely unnecessary database failover. Now on the flip side,'],
  [206, 211, 'a high threshold gives you rock solid stability and way fewer false alarms. But the catch,'],
  [211, 216, 'your users are going to experience a noticeably longer outage before the system finally says,'],
  [216, 221, "okay, yeah, it is really dead, let's failover. So how do we handle this? Well, production systems"],
  [221, 226, 'typically use strict numerical thresholds. A super common magic number is three. You wait for exactly'],
  [226, 230, 'three consecutive failed health checks in a row before officially declaring a component dead.'],
  [230, 236, 'This is the sweet spot. It ensures we are not aggressively triggering a massive recovery'],
  [236, 241, 'just because of a momentary hiccup in the network, but we are still acting fast enough to save the user experience.'],
  [241, 246, 'Now let us talk about the actual infrastructure doing all this heavy lifting with the checking and routing.'],
  [246, 255, 'Section four, load balancers and recovery. In most modern distributed systems, load balancers are the real MVPs,'],
  [255, 261, 'actively using these health checks. And their workflow, it is honestly pretty elegant.'],
  [261, 266, 'First, they continuously ping the backend servers. Second, the moment a server looks sick,'],
  [266, 271, 'they dynamically yank it right out of the rotation. And third, they automatically put it back in once it is fully recovered.'],
  [271, 276, 'So imagine we have 10 FoodDash API servers. If one suddenly stops responding, the load balancer just instantly'],
  [276, 280, 'removes it. It makes sure any new hungry users only get routed to the nine healthy servers,'],
  [280, 285, 'at least until that broken one gets its act together. And honestly, this perfectly illustrates'],
  [285, 290, 'the crazy scalability of this concept, because this exact same detect and reroute principle applies everywhere.'],
  [290, 294, 'It does not matter if you are doing a really small scale failover, just swapping between two local backend servers,'],
  [294, 299, 'or a massive large scale failover, where you are shifting global traffic away from an entire unhealthy geographic region.'],
  [299, 303, 'We are talking about routing millions of users from a completely down data center in Mumbai,'],
  [303, 308, 'straight over to a healthy one in Singapore. At the end of the day, the core logic is exactly the same.'],
  [308, 313, 'But of course, building all this automated failover requires some really careful design around capacity and routing.'],
  [313, 318, 'And that leads us to our next section, chaos engineering and testing failover.'],
  [318, 323, 'There is an absolute golden rule in systems design, and it goes like this.'],
  [323, 328, 'The absolute worst time to discover your failover process is broken, is right in the middle of an actual outage.'],
  [328, 333, 'That is exactly why mature engineering teams practice chaos engineering.'],
  [333, 338, 'They run intense failover drills where they intentionally shut down servers, kill backend processes,'],
  [338, 343, 'or just sever network paths. It sounds crazy, right? But it is absolutely the only way to prove'],
  [343, 348, 'your recovery mechanisms actually work in the real world, long before real paying customers ever feel the impact.'],
  [348, 353, 'All right, let us do a really quick recap of everything we have covered in this explainer.'],
  [353, 358, 'First, health checks detect failures by making sure our systems can actually do useful work.'],
  [358, 363, 'Second, failover kicks in to automatically redirect the traffic. Third, we use strict thresholds'],
  [363, 368, 'to balance our recovery speed against the risk of false positives. Fourth, load balancers are the unsung heroes'],
  [368, 373, 'automating that recovery routing. And finally, failover absolutely 100 percent must be tested.'],
  [373, 378, 'So if you take away just one thing today, let it be this. True availability is not just having backup servers'],
  [378, 383, 'sitting in a closet somewhere. It is what happens when detection, routing, replication, and recovery all work'],
  [383, 388, 'completely seamlessly together. But you know, all of this leaves us with one really provocative question.'],
  [388, 393, 'Let us say our system does recover automatically and super fast. How do we actually measure how much downtime is acceptable?'],
  [393, 398, 'I mean, how do big tech companies define their targets and calculate the real world cost of being down?'],
  [398, 403, 'Well, you will have to join us in our next explainer to find out, because we are going to dive deep into'],
  [403, 408, 'availability targets, uptime percentages, and the famous nines. Make sure you hit subscribe'],
  [408, 426, 'so you do not miss it, and I will see you there.'],
];

const buildWords = (): WordTiming[] => {
  let i = 0;

  return segments.flatMap(([start, end, text]) => {
    const parts = text.trim().split(/\s+/);
    const slot = (end - start) / Math.max(parts.length, 1);

    return parts.map((word, index) => ({
      i: i++,
      text: word,
      start: start + index * slot,
      end: start + (index + 0.92) * slot,
    }));
  });
};

export const words = buildWords();

export const lessonPlan: LessonBeat[] = [
  {id: 'hc-intro-logo', kind: 'hc-screen', start: 0, end: 10, title: 'Engineering Systems', subtitle: 'Availability Patterns Pt.2: Health Checks and Failover', takeaway: 'FoodDash returns as the case study for automatic recovery.'},
  {id: 'hc-intro-architecture', kind: 'hc-screen', start: 10, end: 20, title: 'Part 1 Recap', subtitle: 'Redundancy and replication gave FoodDash a backup.', takeaway: 'The replica is ready, but readiness alone is not recovery.'},
  {id: 'hc-gap-backup', kind: 'hc-screen', start: 20, end: 39, title: 'The Backup Was Ready', subtitle: 'The primary dies, but no one redirects traffic.', takeaway: 'Redundancy alone does not switch traffic.'},
  {id: 'hc-gap-human', kind: 'hc-screen', start: 39, end: 60, title: 'Humans Are Too Slow', subtitle: 'Waiting for manual intervention turns minutes into outage.', takeaway: 'Machines need to detect and route automatically.'},
  {id: 'hc-section-health', kind: 'hc-screen', start: 60, end: 64, title: 'Health Checks', subtitle: 'Detecting Failures', takeaway: 'A health check is a continuous automated test.'},
  {id: 'hc-health-core', kind: 'hc-screen', start: 64, end: 80, title: 'Continuous Automated Test', subtitle: 'Is the component alive and useful?', takeaway: 'Health checks ask whether a component can still serve traffic.'},
  {id: 'hc-health-shallow', kind: 'hc-screen', start: 80, end: 97, title: '200 OK Is Not Enough', subtitle: 'A running process can still be useless.', takeaway: 'A good check verifies downstream dependencies too.'},
  {id: 'hc-health-pyramid', kind: 'hc-screen', start: 97, end: 124, title: 'Health Check Pyramid', subtitle: 'Process, application, and business health.', takeaway: 'True availability means the user can complete the action.'},
  {id: 'hc-health-compare', kind: 'hc-screen', start: 124, end: 132, title: 'True Availability', subtitle: 'Machine on is not the same as useful service.', takeaway: 'The user outcome is the real test.'},
  {id: 'hc-section-failover', kind: 'hc-screen', start: 132, end: 142, title: 'Failover', subtitle: 'Automatic Traffic Redirection', takeaway: 'Failed health checks trigger a recovery plan.'},
  {id: 'hc-failover-setup', kind: 'hc-screen', start: 142, end: 147, title: 'Active-Passive Setup', subtitle: 'Primary handles traffic, replica waits.', takeaway: 'Automatic failover has three distinct steps.'},
  {id: 'hc-failover-detect', kind: 'hc-screen', start: 147, end: 152, title: 'Step 1: Detect', subtitle: 'Three failed checks declare the primary dead.', takeaway: 'Multiple consecutive failures prevent overreaction.'},
  {id: 'hc-failover-promote', kind: 'hc-screen', start: 152, end: 156, title: 'Step 2: Promote', subtitle: 'The replica becomes the new primary.', takeaway: 'The backup must be promoted before it can take traffic.'},
  {id: 'hc-failover-redirect', kind: 'hc-screen', start: 156, end: 171, title: 'Step 3: Redirect', subtitle: 'Traffic bends to the promoted database.', takeaway: 'Automation shrinks an outage to a brief slowdown.'},
  {id: 'hc-threshold-tradeoff', kind: 'hc-screen', start: 171, end: 221, title: 'False Positives', subtitle: 'Speed and stability pull in opposite directions.', takeaway: 'One missed check is too eager, but waiting too long hurts users.'},
  {id: 'hc-threshold-three', kind: 'hc-screen', start: 221, end: 241, title: 'The Magic Number', subtitle: 'Three consecutive failures is the common sweet spot.', takeaway: 'Strict thresholds balance recovery speed with false alarm risk.'},
  {id: 'hc-section-loadbalancer', kind: 'hc-screen', start: 241, end: 246, title: 'Load Balancers', subtitle: 'Checking and routing at the same time.', takeaway: 'The load balancer is the orchestrator.'},
  {id: 'hc-lb-workflow', kind: 'hc-screen', start: 246, end: 271, title: 'Load Balancer Workflow', subtitle: 'Ping, remove, restore.', takeaway: 'The balancer continuously checks the backend pool.'},
  {id: 'hc-lb-pool', kind: 'hc-screen', start: 271, end: 285, title: 'Ten Servers In Rotation', subtitle: 'One sick node leaves, nine keep serving.', takeaway: 'New users route only to healthy servers.'},
  {id: 'hc-lb-global', kind: 'hc-screen', start: 285, end: 313, title: 'Same Principle, Bigger Scale', subtitle: 'Local server failover becomes regional failover.', takeaway: 'Detect, remove, and restore works from one node to whole regions.'},
  {id: 'hc-section-chaos', kind: 'hc-screen', start: 313, end: 323, title: 'Chaos Engineering', subtitle: 'Testing failover before outages.', takeaway: 'The worst time to discover broken failover is during an outage.'},
  {id: 'hc-chaos-outage', kind: 'hc-screen', start: 323, end: 333, title: 'Worst Moment', subtitle: 'Production outage plus untested failover.', takeaway: 'False confidence collapses under real incidents.'},
  {id: 'hc-chaos-drills', kind: 'hc-screen', start: 333, end: 348, title: 'Failover Drills', subtitle: 'Shutdown, kill process, sever network.', takeaway: 'Chaos testing proves recovery before customers feel impact.'},
  {id: 'hc-recap-board', kind: 'hc-screen', start: 348, end: 373, title: 'TL;DR', subtitle: 'The full picture.', takeaway: 'Health checks, failover, thresholds, load balancers, and testing fit together.'},
  {id: 'hc-final-takeaway', kind: 'hc-screen', start: 373, end: 388, title: 'True Availability', subtitle: 'Detection, routing, replication, and recovery together.', takeaway: 'Backups matter only when the recovery loop works.'},
  {id: 'hc-next-question', kind: 'hc-screen', start: 388, end: 408, title: 'Next Question', subtitle: 'How much downtime is acceptable?', takeaway: 'The next explainer moves into uptime targets and the famous nines.'},
  {id: 'hc-outro', kind: 'hc-screen', start: 408, end: 426, title: 'Engineering Systems', subtitle: 'Subscribe for the availability patterns series.', takeaway: 'FoodDash ends healthy, routed, and monitored.'},
];
