import type {LessonBeat} from '../../types';

export const lessonPlan: LessonBeat[] = [
  {
    id: 'fn-01',
    kind: 'fn-screen',
    start: 0,
    end: 7.18,
    title: 'Engineering Systems',
    subtitle: 'Engineering Systems',
    takeaway: 'Reliability targets turn availability into a concrete number.',
  },
  {
    id: 'fn-02',
    kind: 'fn-screen',
    start: 7.18,
    end: 13.74,
    title: 'Resilient FoodDash',
    subtitle: 'A stronger architecture is already in place.',
    takeaway: 'FoodDash can survive failures, but now it needs a target.',
  },
  {
    id: 'fn-03',
    kind: 'fn-screen',
    start: 13.74,
    end: 21.86,
    title: 'CTO Hot Seat',
    subtitle: 'Reliability becomes a stakeholder question.',
    takeaway: 'The platform owner needs one clear answer.',
  },
  {
    id: 'fn-04',
    kind: 'fn-screen',
    start: 21.86,
    end: 26.44,
    title: 'Hungry Customer',
    subtitle: 'Can I order whenever I want?',
    takeaway: 'Availability is visible at the exact moment users need the product.',
  },
  {
    id: 'fn-05',
    kind: 'fn-screen',
    start: 26.44,
    end: 32.34,
    title: 'Restaurant Rush',
    subtitle: 'Will orders keep flowing on Friday night?',
    takeaway: 'Partners care about reliability during peak pressure.',
  },
  {
    id: 'fn-06',
    kind: 'fn-screen',
    start: 32.34,
    end: 37.86,
    title: 'Investor Question',
    subtitle: 'Exactly how reliable is this platform?',
    takeaway: 'Business stakeholders need a number, not a vibe.',
  },
  {
    id: 'fn-07',
    kind: 'fn-screen',
    start: 37.86,
    end: 44.4,
    title: 'Mostly Available Fails',
    subtitle: 'A vague answer does not survive scrutiny.',
    takeaway: 'Availability has to become precise.',
  },
  {
    id: 'fn-08',
    kind: 'fn-screen',
    start: 44.4,
    end: 49.76,
    title: 'Acceptable Downtime',
    subtitle: 'How much outage can FoodDash tolerate?',
    takeaway: 'Reliability targets define the allowed failure budget.',
  },
  {
    id: 'fn-09',
    kind: 'fn-screen',
    start: 49.76,
    end: 59.7,
    title: 'Reorient Architecture',
    subtitle: 'FoodDash already removed single points of failure.',
    takeaway: 'The resilient layout is the foundation for today\'s math.',
  },
  {
    id: 'fn-10',
    kind: 'fn-screen',
    start: 59.7,
    end: 70.62,
    title: 'Resilience Stack',
    subtitle: 'Redundancy, replication, health checks, and failover.',
    takeaway: 'The system can detect failure and bounce back automatically.',
  },
  {
    id: 'fn-11',
    kind: 'fn-screen',
    start: 70.62,
    end: 80.9,
    title: 'Reliability Needs A Number',
    subtitle: 'More architecture requires a harder definition.',
    takeaway: 'Before adding parts, define what reliability means.',
  },
  {
    id: 'fn-12',
    kind: 'fn-screen',
    start: 80.9,
    end: 87.14,
    title: 'Availability Target',
    subtitle: 'The percentage of time the system stays operational.',
    takeaway: 'Availability turns uptime into a measurable percentage.',
  },
  {
    id: 'fn-13',
    kind: 'fn-screen',
    start: 87.14,
    end: 95.62,
    title: 'Famous Nines',
    subtitle: 'Reliability is usually discussed as stacked nines.',
    takeaway: 'Each extra nine tightens the allowed downtime.',
  },
  {
    id: 'fn-14',
    kind: 'fn-screen',
    start: 95.62,
    end: 100.38,
    title: '99 Percent',
    subtitle: 'The baseline tier.',
    takeaway: 'Two nines sounds high, but the budget is still huge.',
  },
  {
    id: 'fn-15',
    kind: 'fn-screen',
    start: 100.38,
    end: 105.36,
    title: '99.9 Percent',
    subtitle: 'One extra nine changes the target.',
    takeaway: 'Three nines makes downtime much tighter.',
  },
  {
    id: 'fn-16',
    kind: 'fn-screen',
    start: 105.36,
    end: 111.02,
    title: '99.99 Percent',
    subtitle: 'Another nine pushes the system harder.',
    takeaway: 'Four nines moves reliability into minutes.',
  },
  {
    id: 'fn-17',
    kind: 'fn-screen',
    start: 111.02,
    end: 120.82,
    title: 'Five Nines',
    subtitle: '99.999% is the holy grail.',
    takeaway: 'Five nines leaves almost no room for error.',
  },
  {
    id: 'fn-18',
    kind: 'fn-screen',
    start: 120.82,
    end: 128.52,
    title: 'Numbers Look Close',
    subtitle: 'The percentages seem almost identical.',
    takeaway: 'Tiny decimals hide major operational differences.',
  },
  {
    id: 'fn-19',
    kind: 'fn-screen',
    start: 128.52,
    end: 136.62,
    title: 'Hidden Downtime',
    subtitle: 'The real difference is allowed outage time.',
    takeaway: 'Availability math is really downtime budgeting.',
  },
  {
    id: 'fn-20',
    kind: 'fn-screen',
    start: 136.62,
    end: 143.54,
    title: 'Physical Time',
    subtitle: 'Measure the target across one full year.',
    takeaway: 'Percentages become concrete when converted to time.',
  },
  {
    id: 'fn-21',
    kind: 'fn-screen',
    start: 143.54,
    end: 149.92,
    title: '3.6 Days',
    subtitle: '99% allows a long outage window.',
    takeaway: 'A holiday weekend outage can still meet a 99% target.',
  },
  {
    id: 'fn-22',
    kind: 'fn-screen',
    start: 149.92,
    end: 158.42,
    title: 'One More Nine',
    subtitle: 'Adding one digit collapses the budget.',
    takeaway: 'The next nine is not a tiny operational change.',
  },
  {
    id: 'fn-23',
    kind: 'fn-screen',
    start: 158.42,
    end: 164.16,
    title: '8.7 Hours',
    subtitle: '99.9% means hours per year.',
    takeaway: 'Three nines shrinks downtime from days to hours.',
  },
  {
    id: 'fn-24',
    kind: 'fn-screen',
    start: 164.16,
    end: 170.2,
    title: '52 Minutes',
    subtitle: '99.99% means less than one hour.',
    takeaway: 'Four nines compresses the annual budget into minutes.',
  },
  {
    id: 'fn-25',
    kind: 'fn-screen',
    start: 170.2,
    end: 180.16,
    title: 'Five Minutes',
    subtitle: 'Five nines leaves only a few minutes annually.',
    takeaway: 'The legendary target has a brutally small margin.',
  },
  {
    id: 'fn-26',
    kind: 'fn-screen',
    start: 180.16,
    end: 189.04,
    title: 'Margin Drops',
    subtitle: 'Every extra nine steepens the reliability curve.',
    takeaway: 'The error budget collapses faster than intuition expects.',
  },
  {
    id: 'fn-27',
    kind: 'fn-screen',
    start: 189.04,
    end: 194.88,
    title: 'Days To Hours',
    subtitle: 'Downtime falls sharply with another nine.',
    takeaway: 'The scale moves from whole days to narrow windows.',
  },
  {
    id: 'fn-28',
    kind: 'fn-screen',
    start: 194.88,
    end: 199.96,
    title: 'Hours To Minutes',
    subtitle: 'Then the window plummets again.',
    takeaway: 'The downtime curve falls off a cliff.',
  },
  {
    id: 'fn-29',
    kind: 'fn-screen',
    start: 199.96,
    end: 206.58,
    title: 'Cost Of Perfection',
    subtitle: 'A shrinking window creates a new engineering problem.',
    takeaway: 'Perfect uptime is an expensive direction, not a free target.',
  },
  {
    id: 'fn-30',
    kind: 'fn-screen',
    start: 206.58,
    end: 212.4,
    title: 'Tiny Improvement',
    subtitle: 'On paper, one more nine looks small.',
    takeaway: 'The percentage delta hides the operational jump.',
  },
  {
    id: 'fn-31',
    kind: 'fn-screen',
    start: 212.4,
    end: 218.2,
    title: 'Expensive Problem',
    subtitle: 'In reality, it creates costly engineering work.',
    takeaway: 'The closer you get to perfect, the more each step costs.',
  },
  {
    id: 'fn-32',
    kind: 'fn-screen',
    start: 218.2,
    end: 224.74,
    title: 'Architecture Balloons',
    subtitle: 'Extra nines force extra moving parts.',
    takeaway: 'Reliability targets shape system topology.',
  },
  {
    id: 'fn-33',
    kind: 'fn-screen',
    start: 224.74,
    end: 232.58,
    title: 'Single To Redundant',
    subtitle: 'Start simple, then add backup servers.',
    takeaway: 'Redundancy is the first visible cost of higher availability.',
  },
  {
    id: 'fn-34',
    kind: 'fn-screen',
    start: 232.58,
    end: 239.36,
    title: 'Load Balancers And Replicas',
    subtitle: 'Traffic management and copied state join the system.',
    takeaway: 'More nines require coordination around compute and data.',
  },
  {
    id: 'fn-35',
    kind: 'fn-screen',
    start: 239.36,
    end: 247.56,
    title: 'Zones And Regions',
    subtitle: 'The last nines push architecture across geography.',
    takeaway: 'Multi-region design is where cost and complexity spike.',
  },
  {
    id: 'fn-36',
    kind: 'fn-screen',
    start: 247.56,
    end: 255.8,
    title: 'Never Free',
    subtitle: 'Every additional nine means more infrastructure.',
    takeaway: 'Availability is paid for in architecture.',
  },
  {
    id: 'fn-37',
    kind: 'fn-screen',
    start: 255.8,
    end: 264.36,
    title: 'Monitoring And Automation',
    subtitle: 'Operations must scale with the architecture.',
    takeaway: 'Infrastructure needs monitoring, automation, testing, and expertise.',
  },
  {
    id: 'fn-38',
    kind: 'fn-screen',
    start: 264.36,
    end: 270.98,
    title: 'Expensive Improvements',
    subtitle: 'Tiny uptime gains become harder and pricier.',
    takeaway: 'The final increments are the hardest to buy.',
  },
  {
    id: 'fn-39',
    kind: 'fn-screen',
    start: 270.98,
    end: 276.68,
    title: 'Business Reality',
    subtitle: 'Now the question leaves pure engineering.',
    takeaway: 'Reliability targets must match business stakes.',
  },
  {
    id: 'fn-40',
    kind: 'fn-screen',
    start: 276.68,
    end: 281.28,
    title: 'Need Five Nines?',
    subtitle: 'Does every system deserve the extreme target?',
    takeaway: 'Not every product path needs maximum uptime.',
  },
  {
    id: 'fn-41',
    kind: 'fn-screen',
    start: 281.28,
    end: 289.82,
    title: 'Is Cost Justified?',
    subtitle: 'Extreme reliability carries extreme complexity.',
    takeaway: 'The target should be justified by real consequence.',
  },
  {
    id: 'fn-42',
    kind: 'fn-screen',
    start: 289.82,
    end: 298.9,
    title: 'Low-Stake Systems',
    subtitle: 'Dashboards and wikis can tolerate 99%.',
    takeaway: 'Internal tools rarely need global failover.',
  },
  {
    id: 'fn-43',
    kind: 'fn-screen',
    start: 298.9,
    end: 302.48,
    title: 'Wiki Overkill',
    subtitle: 'Multi-region failover is too much for a company wiki.',
    takeaway: 'Overbuilding reliability wastes engineering effort.',
  },
  {
    id: 'fn-44',
    kind: 'fn-screen',
    start: 302.48,
    end: 309.96,
    title: 'High-Stake Systems',
    subtitle: 'Payments, emergency networks, and ordering are different.',
    takeaway: 'Critical workflows push toward stronger availability targets.',
  },
  {
    id: 'fn-45',
    kind: 'fn-screen',
    start: 309.96,
    end: 317.32,
    title: 'Revenue And Safety',
    subtitle: 'Minutes of downtime can hurt money or users.',
    takeaway: 'The stakes determine whether five nines makes sense.',
  },
  {
    id: 'fn-46',
    kind: 'fn-screen',
    start: 317.32,
    end: 322.96,
    title: 'Business Trade-Off',
    subtitle: 'The target is not just an engineering puzzle.',
    takeaway: 'Availability is a business decision expressed as engineering work.',
  },
  {
    id: 'fn-47',
    kind: 'fn-screen',
    start: 322.96,
    end: 331.32,
    title: 'Takeaway Targets',
    subtitle: 'Availability targets measure operational time.',
    takeaway: 'Start with the percentage of time the system must operate.',
  },
  {
    id: 'fn-48',
    kind: 'fn-screen',
    start: 331.32,
    end: 339.68,
    title: 'Takeaway Downtime Shrinks',
    subtitle: 'Extra nines pull downtime from days to minutes.',
    takeaway: 'Each added nine sharply reduces the allowed outage budget.',
  },
  {
    id: 'fn-49',
    kind: 'fn-screen',
    start: 339.68,
    end: 347.82,
    title: 'Takeaway Cost Grows',
    subtitle: 'Perfect uptime drives cost and complexity upward.',
    takeaway: 'Near-perfect reliability creates exponential operational pressure.',
  },
  {
    id: 'fn-50',
    kind: 'fn-screen',
    start: 347.82,
    end: 352.5,
    title: 'Math Meets Business',
    subtitle: 'Balance reliability math with business reality.',
    takeaway: 'The right target is the one the product can justify.',
  },
  {
    id: 'fn-51',
    kind: 'fn-screen',
    start: 352.5,
    end: 362.16,
    title: 'Targets Nailed',
    subtitle: 'FoodDash now has healthy redundant servers.',
    takeaway: 'Targets are set, but traffic still needs a routing strategy.',
  },
  {
    id: 'fn-52',
    kind: 'fn-screen',
    start: 362.16,
    end: 369.42,
    title: 'Traffic Distribution',
    subtitle: 'Sprawling infrastructure needs efficient routing.',
    takeaway: 'Availability also depends on how requests are distributed.',
  },
  {
    id: 'fn-53',
    kind: 'fn-screen',
    start: 369.42,
    end: 375.5,
    title: 'Next Request',
    subtitle: 'Which server should receive the next user request?',
    takeaway: 'Healthy capacity must be selected intelligently.',
  },
  {
    id: 'fn-54',
    kind: 'fn-screen',
    start: 375.5,
    end: 380.82,
    title: 'Prevent Overload',
    subtitle: 'Stop one server melting while others sit idle.',
    takeaway: 'Load balancing is the next availability pattern.',
  },
  {
    id: 'fn-55',
    kind: 'fn-screen',
    start: 380.82,
    end: 382.92,
    title: 'Next Puzzle',
    subtitle: 'Traffic distribution is up next.',
    takeaway: 'The next explainer tackles load balancing.',
  },
  {
    id: 'fn-56',
    kind: 'closing',
    start: 382.92,
    end: 389.6,
    title: 'Engineering Systems',
    subtitle: 'See you in the next explainer.',
    takeaway: 'Thanks for watching.',
  },
];
